# Contents

## 01 Import libraries and data

## 02 Check data

### 02.1 Initial consistency checks for data population flow

### 02.2 Check df_p1

### 02.3 Remarks for cleaning on df_p1

### 02.4 Check df_p2

### 02.5 Remarks for cleaning on df_p2

### 02.6 Check df_p3

### 02.7 Remarks for cleaning on df_p3

### 02.8 Check df_p4

### 02.9 Remarks for cleaning on df_p4

### 02.10 Check df_roll

### 02.11 Remarks for cleaning on df_roll

## 03 Data cleaning – individual dataframes

### 03.1 Address mixed-type columns in df_p1

### 03.2 Address mixed-type columns in df_roll

### 03.3 Address column sale_price in all dataframes

### 03.4 Address column sale_date in all dataframes

### 03.5 Harmonise column datatypes in df_p1

### 03.6 Harmonise column datatypes in df_p2

### 03.7 Harmonise column datatypes in df_p3

### 03.8 Harmonise column datatypes in df_p4

### 03.9 Harmonise column datatypes in df_roll

## 04 Final check for mixed-type columns before merging

## 05 Merging all dataframes into one

## 06 Data cleaning - merged dataframe

### 06.1 Address duplicates

### 06.2 Check for missing values

### 06.3 Get descriptive statistics for columns with missing values

### 06.7 Create subsets with missing values

### 06.8 Address missing values

## 07 Creating flags

### 07.1 Sale prices == 0

### 07.2 Imputing borough names

## 08 Data consistency checks

### 08.1 Further cleaning to address inconsistencies

## 09 Basic descriptive statistics I

### 09.1 Further cleaning I based on insights from descriptive statistics

## 10 Basic descriptive statistics II

## 11 Drop columns that are irrelevant for the analysis

## 12 Export dataframes

# 01 Import libraries and data

In [256]:
# Import pandas, numpy, os
import pandas as pd
import numpy as np
import os

In [257]:
# Define path variable
path = r'/Users/DanielaDietmayr/Library/CloudStorage/OneDrive-Personal/2023-05-07_NYC property sales/02_Data/02_Prepared data/01_Ready for import'

In [258]:
# Change options to display all columns
pd.options.display.max_columns = None

In [259]:
# Import data
df_p1 = pd.read_csv(os.path.join(path, '2023-05-07_NYC prop sales 2003-23_P1.csv'), index_col = False)
df_p2 = pd.read_csv(os.path.join(path, '2023-05-07_NYC prop sales 2003-23_P2.csv'), index_col = False)
df_p3 = pd.read_csv(os.path.join(path, '2023-05-07_NYC prop sales 2003-23_P3.csv'), index_col = False)
df_p4 = pd.read_csv(os.path.join(path, '2023-05-07_NYC prop sales 2003-23_P4.csv'), index_col = False)
df_roll = pd.read_csv(os.path.join(path, '2023-05-07_NYC prop sales rolling.csv'), index_col = False)

/var/folders/xf/prw7mx913rn2xzxlywvr1_jc0000gn/T/ipykernel_44932/2658094689.py:6: DtypeWarning: Columns (1,2,3,7,8,9,18,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df_roll = pd.read_csv(os.path.join(path, '2023-05-07_NYC prop sales rolling.csv'), index_col = False)


# 02 Check data

## 02.1 Initial consistency checks for data population flow

According to original data retrieved from NYC Depeartment of Finance website, no data is missing for column sale_date. The numbers of non-missing values for the five dataframes are expected to be as follows:
df_p1: 428903 (Jan 2018 - Dec 2022)
df_p2: 448573 (Jan 2013 - Dec 2017)
df_p3: 499739 (Jan 2007 - Dec 2012)
df_p4: 484134 (Jan 2003 - Dec 2006)
df_roll: 84391 (Apr 2022 - Mar 2023)

Shape of dataframes should hence be 21 columns and rows as indicated above.

In [260]:
# Get shape of df_p1
df_p1.shape

(428903, 21)

In [261]:
# Get shape of df_p2
df_p2.shape

(448573, 21)

In [262]:
# Get shape of df_p3
df_p3.shape

(499793, 21)

In [263]:
# Get shape of df_p4
df_p4.shape

(484134, 21)

In [264]:
# Get shape of df_roll
df_roll.shape

(359913, 21)

Dimensions of df_p1 - p4 are ok. Dimensions of df_roll point to 275522 unexpected rows.

In [265]:
# Check for missing values in sale_date in df_roll
df_roll['sale_date'].value_counts(dropna=False)

NaN         275522
30.06.22       700
28.04.22       589
21.06.22       567
12.07.22       563
             ...  
22.01.23         2
06.11.22         2
03.07.22         2
16.10.22         2
17.04.22         2
Name: sale_date, Length: 366, dtype: int64

In [266]:
# Confirm number of missing values in sale_date
df_roll['sale_date'].isna().sum()

275522

In [267]:
# Drop rows with missing values in sale_date
df_roll.dropna(subset=['sale_date'], inplace=True)

In [268]:
# Confirm dropping of rows
df_roll['sale_date'].isna().sum()

0

In [269]:
df_roll.shape

(84391, 21)

Initial consistency check complete. Dimensions of five dataframes are now as expected according to original data provided by NYC Department of Finance. 

## 02.2 Check df_p1

In [270]:
# Get info on df_p1
df_p1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 428903 entries, 0 to 428902
Data columns (total 21 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   borough                         428903 non-null  int64  
 1   neighborhood                    428903 non-null  object 
 2   building_class_category         428903 non-null  object 
 3   tax_class_at_present            428336 non-null  object 
 4   block                           428903 non-null  int64  
 5   lot                             428903 non-null  int64  
 6   easement                        0 non-null       float64
 7   building_class_at_present       428336 non-null  object 
 8   address                         428903 non-null  object 
 9   apartment_number                100295 non-null  object 
 10  zip_code                        428868 non-null  float64
 11  residential_units               352121 non-null  float64
 12  commercial_units

In [271]:
# Inspect head of df_p1
df_p1.head(5)

borough neighborhood  building_class_category tax_class_at_present  block  \
0        5     ANNADALE  01 ONE FAMILY DWELLINGS                    1   5391   
1        5     ANNADALE  01 ONE FAMILY DWELLINGS                    1   5395   
2        5     ANNADALE  01 ONE FAMILY DWELLINGS                    1   5395   
3        5     ANNADALE  01 ONE FAMILY DWELLINGS                    1   5399   
4        5     ANNADALE  01 ONE FAMILY DWELLINGS                    1   5402   

   lot  easement building_class_at_present              address  \
0    7       NaN                        A5      4732 AMBOY ROAD   
1    4       NaN                        A1      26 EDWIN STREET   
2   32       NaN                        A1  541 SYCAMORE STREET   
3   37       NaN                        A2   255 KOCH BOULEVARD   
4   17       NaN                        A2      6 WEAVER STREET   

  apartment_number             zip_code    residential_units  \
0              NaN            10,312.00                 1.00   
1              NaN            10,312.00                 1.00   
2              NaN            10,312.00                 1.00   
3              NaN            10,312.00                 1.00   
4              NaN            10,312.00                 1.00   

      commercial_units          total_units     land_square_feet  \
0                 0.00                 1.00             3,654.00   
1                 0.00                 1.00             7,654.00   
2                 0.00                 1.00            13,320.00   
3                 0.00                 1.00             8,190.00   
4                 0.00                 1.00            10,500.00   

     gross_square_feet           year_built  tax_class_at_time_of_sale  \
0               910.00             2,002.00                          1   
1             2,277.00             1,980.00                          1   
2             4,696.00             1,985.00                          1   
3             1,528.00             1,970.00                          1   
4             2,278.00             1,980.00                          1   

  building_class_at_time_of_sale      sale_price sale_date  
0                             A5    764,000.00    30.06.22  
1                             A1  1,098,000.00    19.08.22  
2                             A1          0.00    20.04.22  
3                             A2    890,000.00    03.01.22  
4                             A2          0.00    27.12.22

In [272]:
# Check for mixed-type columns in df_p1
for col in df_p1.columns.tolist():
  weird = (df_p1[[col]].applymap(type) != df_p1[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_p1[weird]) > 0:
    print (col)

tax_class_at_present
building_class_at_present
apartment_number


## 02.3 Remarks for cleaning on df_p1
21 columns, 428903 rows.

Only borough number (not name) included.

Missing values imported as NaN. Missing values in columns: easement, building_class_at_present, apartment_number, zip_code, residential_units, commercial_units, total_units, land_square_feet, gross_square_feet, year_built.

ZIP code imported as floating point number.
Residential units imported as floating point number.
Commercial units imported as floating point number.
Total units imported as floating point number.
Year_built imported as floating point number.
Sale_price imported as string.
Sale_date imported as string.

Mixed-type columns are tax class at present, building class at present, and apartment number.

## 02.4 Check df_p2

In [273]:
# Get info on df_p2
df_p2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 448573 entries, 0 to 448572
Data columns (total 21 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   borough                         448573 non-null  int64  
 1   neighborhood                    448573 non-null  object 
 2   building_class_category         448573 non-null  object 
 3   tax_class_at_present            448573 non-null  object 
 4   block                           448573 non-null  int64  
 5   lot                             448573 non-null  int64  
 6   easement                        448573 non-null  object 
 7   building_class_at_present       448573 non-null  object 
 8   address                         448573 non-null  object 
 9   apartment_number                448573 non-null  object 
 10  zip_code                        448573 non-null  int64  
 11  residential_units               448573 non-null  int64  
 12  commercial_units

In [274]:
# Inspect head of df_p2
df_p2.head(5)

borough               neighborhood  \
0        5  ANNADALE                    
1        5  ANNADALE                    
2        5  ANNADALE                    
3        5  ANNADALE                    
4        5  ANNADALE                    

                        building_class_category tax_class_at_present  block  \
0  01  ONE FAMILY DWELLINGS                                        1   5391   
1  01  ONE FAMILY DWELLINGS                                        1   5391   
2  01  ONE FAMILY DWELLINGS                                        1   5395   
3  01  ONE FAMILY DWELLINGS                                        1   5397   
4  01  ONE FAMILY DWELLINGS                                        1   5399   

   lot easement building_class_at_present  \
0    9                                 A5   
1   30                                 A1   
2   15                                 A1   
3   60                                 A1   
4   26                                 A1   

                                     address apartment_number  zip_code  \
0  4726 AMBOY ROAD                                                10312   
1  1306 ARDEN AVENUE                                              10312   
2  10 EDWIN STREET                                                10312   
3  33 EYLANDT STREET                                              10312   
4  235 KOCH BOULEVARD                                             10312   

   residential_units  commercial_units  total_units     land_square_feet  \
0                  1                 0            1             3,067.00   
1                  1                 0            1             7,500.00   
2                  1                 0            1             7,000.00   
3                  1                 0            1            10,120.00   
4                  1                 0            1             9,555.00   

     gross_square_feet  year_built  tax_class_at_time_of_sale  \
0             1,110.00        2002                          1   
1             1,890.00        1952                          1   
2             2,200.00        1980                          1   
3             3,516.00        1984                          1   
4             1,528.00        1960                          1   

  building_class_at_time_of_sale    sale_price sale_date  
0                             A5  520,000.00    21.04.16  
1                             A1        0.00    04.05.16  
2                             A1       10.00    21.04.16  
3                             A1        0.00    10.08.16  
4                             A1        0.00    11.02.16

In [275]:
# Check for mixed-type columns in df_p2
for col in df_p2.columns.tolist():
  weird = (df_p2[[col]].applymap(type) != df_p2[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_p2[weird]) > 0:
    print (col)

## 02.5 Remarks for cleaning on df_p2
21 columns, 448573 rows.

Only borough number (not name) included.

Missing values remain missing (not imported as NaN, but also identified as non-null).

Sale_price imported as string. Sale_date imported as string.

No mixed-type columns.

## 02.6 Check df_p3

In [276]:
# Get info on df_p3
df_p3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 499793 entries, 0 to 499792
Data columns (total 21 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   borough                         499793 non-null  int64  
 1   neighborhood                    499793 non-null  object 
 2   building_class_category         499793 non-null  object 
 3   tax_class_at_present            499793 non-null  object 
 4   block                           499793 non-null  int64  
 5   lot                             499793 non-null  int64  
 6   easement                        499793 non-null  object 
 7   building_class_at_present       499793 non-null  object 
 8   address                         499793 non-null  object 
 9   apartment_number                499793 non-null  object 
 10  zip_code                        499793 non-null  int64  
 11  residential_units               499793 non-null  int64  
 12  commercial_units

In [277]:
# Inspect head of df_p3
df_p3.head(5)

borough               neighborhood  \
0        5  ANNADALE                    
1        5  ANNADALE                    
2        5  ANNADALE                    
3        5  ANNADALE                    
4        5  ANNADALE                    

                        building_class_category tax_class_at_present  block  \
0  01  ONE FAMILY HOMES                                            1   5395   
1  01  ONE FAMILY HOMES                                            1   5401   
2  01  ONE FAMILY HOMES                                            1   5402   
3  01  ONE FAMILY HOMES                                            1   5407   
4  01  ONE FAMILY HOMES                                            1   6205   

   lot easement building_class_at_present  \
0   32                                 A1   
1   38                                 A1   
2   43                                 A1   
3   11                                 A1   
4   23                                 A5   

                                     address apartment_number  zip_code  \
0  541 SYCAMORE STREET                                            10312   
1  27 WEAVER STREET                                               10312   
2  295 HAROLD AVENUE                                              10312   
3  24 ELMBANK STREET                                              10312   
4  81 EAGAN AVENUE                                                10312   

   residential_units  commercial_units  total_units     land_square_feet  \
0                  1                 0            1            13,320.00   
1                  1                 0            1            10,833.00   
2                  1                 0            1             6,700.00   
3                  1                 0            1             5,000.00   
4                  1                 0            1             1,546.00   

     gross_square_feet  year_built  tax_class_at_time_of_sale  \
0             4,696.00        1985                          1   
1             2,128.00        1980                          1   
2             3,348.00        1980                          1   
3             1,520.00        1910                          1   
4             1,579.00        1986                          1   

  building_class_at_time_of_sale      sale_price sale_date  
0                             A1  1,200,000.00    15.08.12  
1                             A1    127,500.00    26.09.12  
2                             A1    600,000.00    31.05.12  
3                             A1    237,276.00    29.11.12  
4                             A5    322,500.00    19.03.12

In [278]:
# Check for mixed-type columns in df_p3
for col in df_p3.columns.tolist():
  weird = (df_p3[[col]].applymap(type) != df_p3[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_p3[weird]) > 0:
    print (col)

## 02.7 Remarks for cleaning on df_p3
21 columns, 499793 rows.

Only borough number (not name) included.

Missing values remain missing (not imported as NaN, but also identified as non-null).

Sale_price imported as string. Sale_date imported as string.

No mixed-type columns.

## 02.8 Check df_p4

In [279]:
# Get info on df_p4
df_p4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 484134 entries, 0 to 484133
Data columns (total 21 columns):
 #   Column                          Non-Null Count   Dtype  
---  ------                          --------------   -----  
 0   borough                         484134 non-null  int64  
 1   neighborhood                    484134 non-null  object 
 2   building_class_category         484134 non-null  object 
 3   tax_class_at_present            484134 non-null  object 
 4   block                           484134 non-null  int64  
 5   lot                             484134 non-null  int64  
 6   easement                        484134 non-null  object 
 7   building_class_at_present       484134 non-null  object 
 8   address                         484134 non-null  object 
 9   apartment_number                484134 non-null  object 
 10  zip_code                        484134 non-null  int64  
 11  residential_units               484134 non-null  int64  
 12  commercial_units

In [280]:
# Inspect head of df_p4
df_p4.head(5)

borough               neighborhood  \
0        5  ANNADALE                    
1        5  ANNADALE                    
2        5  ANNADALE                    
3        5  ANNADALE                    
4        5  ANNADALE                    

                        building_class_category tax_class_at_present  block  \
0  01  ONE FAMILY HOMES                                            1   5394   
1  01  ONE FAMILY HOMES                                            1   5395   
2  01  ONE FAMILY HOMES                                            1   5395   
3  01  ONE FAMILY HOMES                                            1   5396   
4  01  ONE FAMILY HOMES                                            1   5397   

   lot easement building_class_at_present  \
0    8                                 A1   
1    4                                 A1   
2   19                                 A1   
3   46                                 A1   
4    7                                 A1   

                                     address apartment_number  zip_code  \
0  16 FINGAL STREET                                               10312   
1  26 EDWIN STREET                                                10312   
2  4 EDWIN STREET                                                 10312   
3  31 TALLMAN STREET                                              10312   
4  20 TALLMAN STREET                                              10312   

   residential_units  commercial_units  total_units     land_square_feet  \
0                  1                 0            1            10,000.00   
1                  1                 0            1             7,654.00   
2                  1                 0            1             7,258.00   
3                  1                 0            1            10,080.00   
4                  1                 0            1            10,800.00   

     gross_square_feet  year_built  tax_class_at_time_of_sale  \
0             5,163.00        1985                          1   
1             2,277.00        1980                          1   
2             2,230.00        1980                          1   
3             4,400.00        1991                          1   
4             4,157.00        1984                          1   

  building_class_at_time_of_sale      sale_price sale_date  
0                             A1  1,360,000.00    21.07.06  
1                             A1    900,000.00    05.09.06  
2                             A1    785,000.00    21.07.06  
3                             A1  1,200,000.00    27.09.06  
4                             A1  1,094,500.00    12.05.06

In [281]:
# Check for mixed-type columns in df_p4
for col in df_p4.columns.tolist():
  weird = (df_p4[[col]].applymap(type) != df_p4[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_p4[weird]) > 0:
    print (col)

## 02.9 Remarks for cleaning on df_p4
21 columns, 484134 rows.

Only borough number (not name) included.

Missing values remain missing (not imported as NaN, but also identified as non-null).

Sale_price imported as string. Sale_date imported as string.

No mixed-type columns.

## 02.10 Check df_roll

In [282]:
# Get info on df_roll
df_roll.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 84391 entries, 0 to 84390
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   borough                         84391 non-null  float64
 1   neighborhood                    84391 non-null  object 
 2   building_class_category         84391 non-null  object 
 3   tax_class_at_present            84310 non-null  object 
 4   block                           84391 non-null  float64
 5   lot                             84391 non-null  float64
 6   easement                        0 non-null      float64
 7   building_class_at_present       84310 non-null  object 
 8   address                         84391 non-null  object 
 9   apartment_number                21338 non-null  object 
 10  zip_code                        84384 non-null  float64
 11  residential_units               63144 non-null  float64
 12  commercial_units                

In [283]:
# Inspect head of df_roll
df_roll.head(5)

borough neighborhood  building_class_category  \
0                 5.00     ANNADALE  01 ONE FAMILY DWELLINGS   
1                 5.00     ANNADALE  01 ONE FAMILY DWELLINGS   
2                 5.00     ANNADALE  01 ONE FAMILY DWELLINGS   
3                 5.00     ANNADALE  01 ONE FAMILY DWELLINGS   
4                 5.00     ANNADALE  01 ONE FAMILY DWELLINGS   

  tax_class_at_present                block                  lot  easement  \
0                    1             5,391.00                 7.00       NaN   
1                    1             5,395.00                 4.00       NaN   
2                    1             5,395.00                32.00       NaN   
3                    1             5,396.00                41.00       NaN   
4                    1             5,401.00                42.00       NaN   

  building_class_at_present              address apartment_number  \
0                        A5      4732 AMBOY ROAD              NaN   
1                        A1      26 EDWIN STREET              NaN   
2                        A1  541 SYCAMORE STREET              NaN   
3                        A1    21 TALLMAN STREET              NaN   
4                        A2    265 HAROLD AVENUE              NaN   

              zip_code    residential_units     commercial_units  \
0            10,312.00                 1.00                 0.00   
1            10,312.00                 1.00                 0.00   
2            10,312.00                 1.00                 0.00   
3            10,312.00                 1.00                 0.00   
4            10,312.00                 1.00                 0.00   

           total_units     land_square_feet    gross_square_feet  \
0                 1.00             3,655.00               910.00   
1                 1.00             7,654.00             2,277.00   
2                 1.00            13,320.00             4,696.00   
3                 1.00             9,968.00             3,940.00   
4                 1.00             8,190.00             2,100.00   

            year_built  tax_class_at_time_of_sale  \
0             2,002.00                       1.00   
1             1,980.00                       1.00   
2             1,985.00                       1.00   
3             1,990.00                       1.00   
4             1,980.00                       1.00   

  building_class_at_time_of_sale      sale_price sale_date  
0                             A5    764,000.00    30.06.22  
1                             A1  1,098,000.00    19.08.22  
2                             A1          0.00    20.04.22  
3                             A1  1,275,000.00    17.03.23  
4                             A2    385,000.00    16.02.23

In [284]:
# Check for mixed-type columns in df_roll
for col in df_roll.columns.tolist():
  weird = (df_roll[[col]].applymap(type) != df_roll[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_roll[weird]) > 0:
    print (col)

tax_class_at_present
building_class_at_present
apartment_number


## 02.11 Remarks for cleaning on df_roll
21 columns, 84391 rows.

Missing values imported as NaN. Missing values in: tax_class_at_present, easement, building_class_at_present, apartment_number, zip_code, residential_units, commercial_units, total_units, land_square_feet, cross_square_feet, year_built

Borough imported as floating point number.
Only borough number (not name) included.
Block imported as floating point number.
Lot imported as floating point number.
ZIP code imported as floating point number.
Residential units imported as floating point number.
Commercial units imported as floating point number.
Total units imported as floating point number.
Year built imported as floating point number.
Tax class at time of sale imported as floating point number.
Sale_price imported as string. 
Sale_date imported as string.

Mixed type columns are tax class at present, building class at present, apartment number. 

# 03 Data cleaning - individual dataframes

## 03.1 Address mixed-type columns in df_p1

In [285]:
# Fix mixed data types in df_p1
df_p1['tax_class_at_present'] = df_p1['tax_class_at_present'].astype('str')
df_p1['building_class_at_present'] = df_p1['building_class_at_present'].astype('str')
df_p1['apartment_number'] = df_p1['apartment_number'].astype('str')

In [286]:
# Check for fixing mixed-type columns in df_p1
for col in df_p1.columns.tolist():
  weird = (df_p1[[col]].applymap(type) != df_p1[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_p1[weird]) > 0:
    print (col)

No mixed-type columns remain in df_p1.

## 03.2 Address mixed-type columns in df_roll

In [287]:
# Fix mixed data types in df_roll
df_roll['tax_class_at_present'] = df_roll['tax_class_at_present'].astype('str')
df_roll['building_class_at_present'] = df_roll['building_class_at_present'].astype('str')
df_roll['apartment_number'] = df_roll['apartment_number'].astype('str')

In [288]:
# Check again for mixed-type columns in df_roll
for col in df_roll.columns.tolist():
  weird = (df_roll[[col]].applymap(type) != df_roll[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_roll[weird]) > 0:
    print (col)

No mixed-type columns remain in df_roll.

## 03.3 Address column sale_price in all dataframes

In [289]:
# Remove commas from column sale_price to prepare for conversion to floating point number
df_p1['sale_price'] = df_p1['sale_price'].str.replace(',','')
df_p2['sale_price'] = df_p2['sale_price'].str.replace(',','')
df_p3['sale_price'] = df_p3['sale_price'].str.replace(',','')
df_p4['sale_price'] = df_p4['sale_price'].str.replace(',','')
df_roll['sale_price'] = df_roll['sale_price'].str.replace(',','')

In [290]:
# Convert sale_price to floating point number
df_p1['sale_price'] = df_p1['sale_price'].astype('float')
df_p2['sale_price'] = df_p2['sale_price'].astype('float')
df_p3['sale_price'] = df_p3['sale_price'].astype('float')
df_p4['sale_price'] = df_p4['sale_price'].astype('float')
df_roll['sale_price'] = df_roll['sale_price'].astype('float')

In [291]:
# Check whether data type for sale_price was converted for df_p1
df_p1['sale_price'].dtype

dtype('float64')

In [292]:
# Check whether data type for sale_price was converted for df_p2
df_p2['sale_price'].dtype

dtype('float64')

In [293]:
# Check whether data type for sale_price was converted for df_p3
df_p3['sale_price'].dtype

dtype('float64')

In [294]:
# Check whether data type for sale_price was converted for df_p4
df_p4['sale_price'].dtype

dtype('float64')

In [295]:
# Check whether data type for sale_price was converted for df_roll
df_roll['sale_price'].dtype

dtype('float64')

In [296]:
# Check how values in df_p1 look after conversion of sale_price
df_p1.head(2)

borough neighborhood  building_class_category tax_class_at_present  block  \
0        5     ANNADALE  01 ONE FAMILY DWELLINGS                    1   5391   
1        5     ANNADALE  01 ONE FAMILY DWELLINGS                    1   5395   

   lot  easement building_class_at_present          address apartment_number  \
0    7       NaN                        A5  4732 AMBOY ROAD              nan   
1    4       NaN                        A1  26 EDWIN STREET              nan   

              zip_code    residential_units     commercial_units  \
0            10,312.00                 1.00                 0.00   
1            10,312.00                 1.00                 0.00   

           total_units     land_square_feet    gross_square_feet  \
0                 1.00             3,654.00               910.00   
1                 1.00             7,654.00             2,277.00   

            year_built  tax_class_at_time_of_sale  \
0             2,002.00                          1   
1             1,980.00                          1   

  building_class_at_time_of_sale           sale_price sale_date  
0                             A5           764,000.00  30.06.22  
1                             A1         1,098,000.00  19.08.22

In [297]:
# Check how values in df_p2 look after conversion of sale_price
df_p2.head(2)

borough               neighborhood  \
0        5  ANNADALE                    
1        5  ANNADALE                    

                        building_class_category tax_class_at_present  block  \
0  01  ONE FAMILY DWELLINGS                                        1   5391   
1  01  ONE FAMILY DWELLINGS                                        1   5391   

   lot easement building_class_at_present  \
0    9                                 A5   
1   30                                 A1   

                                     address apartment_number  zip_code  \
0  4726 AMBOY ROAD                                                10312   
1  1306 ARDEN AVENUE                                              10312   

   residential_units  commercial_units  total_units     land_square_feet  \
0                  1                 0            1             3,067.00   
1                  1                 0            1             7,500.00   

     gross_square_feet  year_built  tax_class_at_time_of_sale  \
0             1,110.00        2002                          1   
1             1,890.00        1952                          1   

  building_class_at_time_of_sale           sale_price sale_date  
0                             A5           520,000.00  21.04.16  
1                             A1                 0.00  04.05.16

In [298]:
# Check how values in df_p3 look after conversion of sale_price
df_p3.head(2)

borough               neighborhood  \
0        5  ANNADALE                    
1        5  ANNADALE                    

                        building_class_category tax_class_at_present  block  \
0  01  ONE FAMILY HOMES                                            1   5395   
1  01  ONE FAMILY HOMES                                            1   5401   

   lot easement building_class_at_present  \
0   32                                 A1   
1   38                                 A1   

                                     address apartment_number  zip_code  \
0  541 SYCAMORE STREET                                            10312   
1  27 WEAVER STREET                                               10312   

   residential_units  commercial_units  total_units     land_square_feet  \
0                  1                 0            1            13,320.00   
1                  1                 0            1            10,833.00   

     gross_square_feet  year_built  tax_class_at_time_of_sale  \
0             4,696.00        1985                          1   
1             2,128.00        1980                          1   

  building_class_at_time_of_sale           sale_price sale_date  
0                             A1         1,200,000.00  15.08.12  
1                             A1           127,500.00  26.09.12

In [299]:
# Check how values in df_p4 look after conversion of sale_price
df_p4.head(2)

borough               neighborhood  \
0        5  ANNADALE                    
1        5  ANNADALE                    

                        building_class_category tax_class_at_present  block  \
0  01  ONE FAMILY HOMES                                            1   5394   
1  01  ONE FAMILY HOMES                                            1   5395   

   lot easement building_class_at_present  \
0    8                                 A1   
1    4                                 A1   

                                     address apartment_number  zip_code  \
0  16 FINGAL STREET                                               10312   
1  26 EDWIN STREET                                                10312   

   residential_units  commercial_units  total_units     land_square_feet  \
0                  1                 0            1            10,000.00   
1                  1                 0            1             7,654.00   

     gross_square_feet  year_built  tax_class_at_time_of_sale  \
0             5,163.00        1985                          1   
1             2,277.00        1980                          1   

  building_class_at_time_of_sale           sale_price sale_date  
0                             A1         1,360,000.00  21.07.06  
1                             A1           900,000.00  05.09.06

In [300]:
# Check how values in df_roll look after conversion of sale_price
df_roll.head(2)

borough neighborhood  building_class_category  \
0                 5.00     ANNADALE  01 ONE FAMILY DWELLINGS   
1                 5.00     ANNADALE  01 ONE FAMILY DWELLINGS   

  tax_class_at_present                block                  lot  easement  \
0                    1             5,391.00                 7.00       NaN   
1                    1             5,395.00                 4.00       NaN   

  building_class_at_present          address apartment_number  \
0                        A5  4732 AMBOY ROAD              nan   
1                        A1  26 EDWIN STREET              nan   

              zip_code    residential_units     commercial_units  \
0            10,312.00                 1.00                 0.00   
1            10,312.00                 1.00                 0.00   

           total_units     land_square_feet    gross_square_feet  \
0                 1.00             3,655.00               910.00   
1                 1.00             7,654.00             2,277.00   

            year_built  tax_class_at_time_of_sale  \
0             2,002.00                       1.00   
1             1,980.00                       1.00   

  building_class_at_time_of_sale           sale_price sale_date  
0                             A5           764,000.00  30.06.22  
1                             A1         1,098,000.00  19.08.22

Columns sale_price in all dataframes converted.

## 03.4 Address column sale_date in all dataframes

In [301]:
# Convert sale_date to datetime
df_p1['sale_date'] = pd.to_datetime(df_p1['sale_date'], format='%d.%m.%y')
df_p2['sale_date'] = pd.to_datetime(df_p2['sale_date'], format='%d.%m.%y')
df_p3['sale_date'] = pd.to_datetime(df_p3['sale_date'], format='%d.%m.%y')
df_p4['sale_date'] = pd.to_datetime(df_p4['sale_date'], format='%d.%m.%y')
df_roll['sale_date'] = pd.to_datetime(df_roll['sale_date'], format='%d.%m.%y')

In [302]:
# Get minimum sale_date in df_p1 (expected: 01/01/2018)
df_p1['sale_date'].min()

Timestamp('2018-01-01 00:00:00')

In [303]:
# Get maximum sale_date in df_p1 (expected: 31/12/2022)
df_p1['sale_date'].max()

Timestamp('2022-12-31 00:00:00')

In [304]:
# Get minimum sale_date in df_p2 (expected: 01/01/2013)
df_p2['sale_date'].min()

Timestamp('2013-01-01 00:00:00')

In [305]:
# Get maximum sale_date in df_p2 (expected: 31/12/2017)
df_p2['sale_date'].max()

Timestamp('2017-12-31 00:00:00')

In [306]:
# Get minimum sale_date in df_p3 (expected: 01/01/2007)
df_p3['sale_date'].min()

Timestamp('2007-01-01 00:00:00')

In [307]:
# Get maximum sale_date in df_p3 (expected: 31/12/2012)
df_p3['sale_date'].max()

Timestamp('2012-12-31 00:00:00')

In [308]:
# Get minimum sale_date in df_p4 (expected: 01/01/2003)
df_p4['sale_date'].min()

Timestamp('2003-01-01 00:00:00')

In [309]:
# Get maximum sale_date in df_p4 (expected: 31/12/2006)
df_p4['sale_date'].max()

Timestamp('2006-12-31 00:00:00')

In [310]:
# Get minimum sale_date in df_roll (expected: 01/04/2022)
df_roll['sale_date'].min()

Timestamp('2022-04-01 00:00:00')

In [311]:
# Get maximum sale_date in df_roll (expected: 31/03/2023)
df_roll['sale_date'].max()

Timestamp('2023-03-31 00:00:00')

In [312]:
# Get sale_date datatype in df_p1
df_p1['sale_date'].dtypes

dtype('<M8[ns]')

In [313]:
# Get sale_date datatype in df_p2
df_p2['sale_date'].dtypes

dtype('<M8[ns]')

In [314]:
# Get sale_date datatype in df_p3
df_p3['sale_date'].dtypes

dtype('<M8[ns]')

In [315]:
# Get sale_date datatype in df_p4
df_p4['sale_date'].dtypes

dtype('<M8[ns]')

In [316]:
# Get sale_date datatype in df_roll
df_roll['sale_date'].dtypes

dtype('<M8[ns]')

Columns sale_date in all dataframes converted, minimum and maximum dates as expected.

## 03.5 Harmonise column datatypes in df_p1

In [317]:
# Recall datatypes in df_p1
df_p1.dtypes

borough                                    int64
neighborhood                              object
building_class_category                   object
tax_class_at_present                      object
block                                      int64
lot                                        int64
easement                                 float64
building_class_at_present                 object
address                                   object
apartment_number                          object
zip_code                                 float64
residential_units                        float64
commercial_units                         float64
total_units                              float64
land_square_feet                         float64
gross_square_feet                        float64
year_built                               float64
tax_class_at_time_of_sale                  int64
building_class_at_time_of_sale            object
sale_price                               float64
sale_date           

In [318]:
# Convert borough, block and lot to string
df_p1['borough'] = df_p1['borough'].astype('str')
df_p1['block'] = df_p1['block'].astype('str')
df_p1['lot'] = df_p1['lot'].astype('str')

# Convert easement to string
df_p1['easement'] = df_p1['easement'].astype('str').str[:-2]

# Convert zip_code to int
df_p1['zip_code'] = df_p1['zip_code'].astype(int, errors='ignore')

# Convert columns on numbers of units to int
df_p1['residential_units'] = df_p1['residential_units'].astype(int, errors='ignore')
df_p1['commercial_units'] = df_p1['commercial_units'].astype(int, errors='ignore')
df_p1['total_units'] = df_p1['total_units'].astype(int, errors='ignore')

# Convert year_built to int
df_p1['year_built'] = df_p1['year_built'].astype(int, errors='ignore')

# Convert tax_class_at_time_of_sale to string
df_p1['tax_class_at_time_of_sale'] = df_p1['tax_class_at_time_of_sale'].astype('str')

In [319]:
# Check whether conversion has worked
df_p1.dtypes

borough                                   object
neighborhood                              object
building_class_category                   object
tax_class_at_present                      object
block                                     object
lot                                       object
easement                                  object
building_class_at_present                 object
address                                   object
apartment_number                          object
zip_code                                 float64
residential_units                        float64
commercial_units                         float64
total_units                              float64
land_square_feet                         float64
gross_square_feet                        float64
year_built                               float64
tax_class_at_time_of_sale                 object
building_class_at_time_of_sale            object
sale_price                               float64
sale_date           

Conversion has not worked for zip_code, residential_units, commercial_units, total_units and year_built. 

In [320]:
# Check zip_code for missing values
df_p1['zip_code'].isna().sum()

35

In [321]:
# Change options to display 10+ rows when printing a dataframe
pd.options.display.max_rows = None

In [322]:
# Inspect rows with missing values for zip_code
print(df_p1.loc[df_p1['zip_code'].isna()])

       borough              neighborhood            building_class_category  \
591          5                BLOOMFIELD          31 COMMERCIAL VACANT LAND   
5479         5             OAKWOOD-BEACH         05 TAX CLASS 1 VACANT LAND   
8869         4                   ARVERNE              29 COMMERCIAL GARAGES   
83458        3              SPRING CREEK         05 TAX CLASS 1 VACANT LAND   
83459        3              SPRING CREEK         05 TAX CLASS 1 VACANT LAND   
83460        3              SPRING CREEK         05 TAX CLASS 1 VACANT LAND   
83461        3              SPRING CREEK         05 TAX CLASS 1 VACANT LAND   
99726        5             OAKWOOD-BEACH         05 TAX CLASS 1 VACANT LAND   
193328       5                BULLS HEAD         05 TAX CLASS 1 VACANT LAND   
193329       5                BULLS HEAD         05 TAX CLASS 1 VACANT LAND   
193330       5                BULLS HEAD         05 TAX CLASS 1 VACANT LAND   
193331       5                BULLS HEAD         05 

Theoretically, missing zip codes could be imputed by deducing the correct zip code from the address. However, this is only possible in cases where the full address is available (only 3/35 cases). Furthermore, zip codes won't be crucial for gaining insights (instead neighborhoods and boroughs are crucial). Therefore, missing values will be imputed as 0.

In [323]:
# Imputing 0 for missing values in zip_code
df_p1['zip_code'].fillna(0, inplace=True)

In [324]:
# Check whether missing values were imputed
df_p1['zip_code'].isna().sum()

0

In [325]:
# Check residential_units for missing values
df_p1['residential_units'].isna().sum()

76782

In [326]:
# Change options to display max rows when printing a dataframe
pd.options.display.max_rows = 30

In [327]:
# Inspect some rows with missing values for residential_units
print(df_p1.loc[df_p1['residential_units'].isna()])

       borough          neighborhood            building_class_category  \
199          5              ANNADALE           46 CONDO STORE BUILDINGS   
200          5              ANNADALE           46 CONDO STORE BUILDINGS   
573          5  ARROCHAR-SHORE ACRES     10 COOPS - ELEVATOR APARTMENTS   
574          5  ARROCHAR-SHORE ACRES     10 COOPS - ELEVATOR APARTMENTS   
575          5  ARROCHAR-SHORE ACRES     10 COOPS - ELEVATOR APARTMENTS   
...        ...                   ...                                ...   
401843       3          BOROUGH PARK  15 CONDOS - 2-10 UNIT RESIDENTIAL   
402413       3        BRIGHTON BEACH  15 CONDOS - 2-10 UNIT RESIDENTIAL   
402414       3        BRIGHTON BEACH  15 CONDOS - 2-10 UNIT RESIDENTIAL   
419658       3  WILLIAMSBURG-CENTRAL    13 CONDOS - ELEVATOR APARTMENTS   
420166       3    WILLIAMSBURG-NORTH                  11A CONDO-RENTALS   

       tax_class_at_present block   lot easement building_class_at_present  \
199                  

In [328]:
# Get basic descriptive statistics on residential_units
df_p1['residential_units'].describe()

count             352,121.00
mean                    2.65
std                    23.76
min                     0.00
25%                     1.00
50%                     1.00
75%                     2.00
max                 8,764.00
Name: residential_units, dtype: float64

In [329]:
# Check skewness of residential_units
df_p1['residential_units'].skew()

156.56594874472592

As distribution in residential_units is highly skewed and the number of missing values is high (ca. 17% of all rows) and dropping them might delete valuable information in other columns, missing values will be imputed with median. 

In [330]:
# Impute missing values in residential_units with median
df_p1['residential_units'].fillna(df_p1['residential_units'].median(), inplace=True)

In [331]:
# Check whether missing values were imputed
df_p1['residential_units'].isna().sum()

0

In [332]:
# Check commercial_units for missing values
df_p1['commercial_units'].isna().sum()

113638

In [333]:
# Inspect some rows with missing values for commercial_units
print(df_p1.loc[df_p1['commercial_units'].isna()])

       borough          neighborhood            building_class_category  \
180          5              ANNADALE              04 TAX CLASS 1 CONDOS   
468          5         ARDEN HEIGHTS              04 TAX CLASS 1 CONDOS   
469          5         ARDEN HEIGHTS              04 TAX CLASS 1 CONDOS   
470          5         ARDEN HEIGHTS              04 TAX CLASS 1 CONDOS   
471          5         ARDEN HEIGHTS              04 TAX CLASS 1 CONDOS   
...        ...                   ...                                ...   
401843       3          BOROUGH PARK  15 CONDOS - 2-10 UNIT RESIDENTIAL   
402413       3        BRIGHTON BEACH  15 CONDOS - 2-10 UNIT RESIDENTIAL   
402414       3        BRIGHTON BEACH  15 CONDOS - 2-10 UNIT RESIDENTIAL   
419658       3  WILLIAMSBURG-CENTRAL    13 CONDOS - ELEVATOR APARTMENTS   
420166       3    WILLIAMSBURG-NORTH                  11A CONDO-RENTALS   

       tax_class_at_present block   lot easement building_class_at_present  \
180                  

In [334]:
# Get basic descriptive statistics on commercial_units
df_p1['commercial_units'].describe()

count             315,265.00
mean                    0.30
std                     7.02
min                     0.00
25%                     0.00
50%                     0.00
75%                     0.00
max                 2,261.00
Name: commercial_units, dtype: float64

In [335]:
# Check skewness of commercial_units
df_p1['commercial_units'].skew()

155.87936242235176

As distribution in residential_units is highly skewed and the number of missing values is high (ca. 26% of all rows) and dropping them might delete valuable information in other columns, missing values will be imputed with median. 

In [336]:
# Impute missing values in commercial_units with median
df_p1['commercial_units'].fillna(df_p1['commercial_units'].median(), inplace=True)

In [337]:
# Check whether missing values were imputed
df_p1['commercial_units'].isna().sum()

0

In [338]:
# Check total_units for missing values
df_p1['total_units'].isna().sum()

70762

In [339]:
# Inspect some rows with missing values for total_units
print(df_p1.loc[df_p1['total_units'].isna()])

       borough          neighborhood            building_class_category  \
573          5  ARROCHAR-SHORE ACRES     10 COOPS - ELEVATOR APARTMENTS   
574          5  ARROCHAR-SHORE ACRES     10 COOPS - ELEVATOR APARTMENTS   
575          5  ARROCHAR-SHORE ACRES     10 COOPS - ELEVATOR APARTMENTS   
576          5  ARROCHAR-SHORE ACRES     10 COOPS - ELEVATOR APARTMENTS   
577          5  ARROCHAR-SHORE ACRES     10 COOPS - ELEVATOR APARTMENTS   
...        ...                   ...                                ...   
401843       3          BOROUGH PARK  15 CONDOS - 2-10 UNIT RESIDENTIAL   
402413       3        BRIGHTON BEACH  15 CONDOS - 2-10 UNIT RESIDENTIAL   
402414       3        BRIGHTON BEACH  15 CONDOS - 2-10 UNIT RESIDENTIAL   
419658       3  WILLIAMSBURG-CENTRAL    13 CONDOS - ELEVATOR APARTMENTS   
420166       3    WILLIAMSBURG-NORTH                  11A CONDO-RENTALS   

       tax_class_at_present block   lot easement building_class_at_present  \
573                  

Missing values for total_units will be deduced from residential_units + commercial_units.

In [340]:
# Impute missing values in total_units
df_p1['total_units'].fillna((df_p1['residential_units']+df_p1['commercial_units']), inplace=True)

In [341]:
# Check whether missing values were imputed
df_p1['total_units'].isna().sum()

0

In [342]:
# Print row at index 420166 to check whether correct value was imputed (expected value is 1.0)
print(df_p1.iloc[[420166]])

       borough        neighborhood building_class_category  \
420166       3  WILLIAMSBURG-NORTH       11A CONDO-RENTALS   

       tax_class_at_present block   lot easement building_class_at_present  \
420166                  nan  2358  1304        n                       nan   

                    address apartment_number             zip_code  \
420166  94 NORTH 3RD STREET              AFF            11,249.00   

          residential_units     commercial_units          total_units  \
420166                 1.00                 0.00                 1.00   

        land_square_feet  gross_square_feet           year_built  \
420166               NaN                NaN             2,017.00   

       tax_class_at_time_of_sale building_class_at_time_of_sale  \
420166                         2                             RR   

                 sale_price  sale_date  
420166                 0.00 2018-05-15  


In [343]:
# Check year_built for missing values
df_p1['year_built'].isna().sum()

24025

In [344]:
# Inspect some rows with missing values for year_built
print(df_p1.loc[df_p1['year_built'].isna()])

       borough        neighborhood            building_class_category  \
181          5            ANNADALE         05 TAX CLASS 1 VACANT LAND   
184          5            ANNADALE         05 TAX CLASS 1 VACANT LAND   
185          5            ANNADALE         05 TAX CLASS 1 VACANT LAND   
186          5            ANNADALE         05 TAX CLASS 1 VACANT LAND   
188          5            ANNADALE         05 TAX CLASS 1 VACANT LAND   
...        ...                 ...                                ...   
345025       2      WILLIAMSBRIDGE              29 COMMERCIAL GARAGES   
345027       2      WILLIAMSBRIDGE          31 COMMERCIAL VACANT LAND   
347874       5         GREAT KILLS            01 ONE FAMILY DWELLINGS   
399782       3  BEDFORD STUYVESANT  15 CONDOS - 2-10 UNIT RESIDENTIAL   
399783       3  BEDFORD STUYVESANT  15 CONDOS - 2-10 UNIT RESIDENTIAL   

       tax_class_at_present block   lot easement building_class_at_present  \
181                      1B  6242    17      

In some cases, missing values in year_built could point towards empty land (cf. building class category). However, this does not apply to all rows with missing values, so it is unclear how missing values in year_built can be reasonably imputed. Imputing mean or median does not make sense either in the case of year figures as it is unclear whether they are missing at random or with a pattern. Missing values make up ca. 5,6% of all rows. They will be dropped. 

In [345]:
# Drop rows with missing values in year_built
df_p1.dropna(subset=['year_built'], inplace=True)

In [346]:
# Check whether missing values were dropped
df_p1['year_built'].isna().sum()

0

No missing values remain in the columns not converted to integers. 

In [347]:
# Convert zip_code to int
df_p1['zip_code'] = df_p1['zip_code'].astype(int, errors='ignore')

# Convert columns on numbers of units to int
df_p1['residential_units'] = df_p1['residential_units'].astype(int, errors='ignore')
df_p1['commercial_units'] = df_p1['commercial_units'].astype(int, errors='ignore')
df_p1['total_units'] = df_p1['total_units'].astype(int, errors='ignore')

# Convert year_built to int
df_p1['year_built'] = df_p1['year_built'].astype(int, errors='ignore')

In [348]:
# Check datatypes in df_p1
df_p1.dtypes

borough                                   object
neighborhood                              object
building_class_category                   object
tax_class_at_present                      object
block                                     object
lot                                       object
easement                                  object
building_class_at_present                 object
address                                   object
apartment_number                          object
zip_code                                   int64
residential_units                          int64
commercial_units                           int64
total_units                                int64
land_square_feet                         float64
gross_square_feet                        float64
year_built                                 int64
tax_class_at_time_of_sale                 object
building_class_at_time_of_sale            object
sale_price                               float64
sale_date           

In [349]:
# Check head of df_p1
df_p1.head()

borough neighborhood  building_class_category tax_class_at_present block  \
0       5     ANNADALE  01 ONE FAMILY DWELLINGS                    1  5391   
1       5     ANNADALE  01 ONE FAMILY DWELLINGS                    1  5395   
2       5     ANNADALE  01 ONE FAMILY DWELLINGS                    1  5395   
3       5     ANNADALE  01 ONE FAMILY DWELLINGS                    1  5399   
4       5     ANNADALE  01 ONE FAMILY DWELLINGS                    1  5402   

  lot easement building_class_at_present              address  \
0   7        n                        A5      4732 AMBOY ROAD   
1   4        n                        A1      26 EDWIN STREET   
2  32        n                        A1  541 SYCAMORE STREET   
3  37        n                        A2   255 KOCH BOULEVARD   
4  17        n                        A2      6 WEAVER STREET   

  apartment_number  zip_code  residential_units  commercial_units  \
0              nan     10312                  1                 0   
1              nan     10312                  1                 0   
2              nan     10312                  1                 0   
3              nan     10312                  1                 0   
4              nan     10312                  1                 0   

   total_units     land_square_feet    gross_square_feet  year_built  \
0            1             3,654.00               910.00        2002   
1            1             7,654.00             2,277.00        1980   
2            1            13,320.00             4,696.00        1985   
3            1             8,190.00             1,528.00        1970   
4            1            10,500.00             2,278.00        1980   

  tax_class_at_time_of_sale building_class_at_time_of_sale  \
0                         1                             A5   
1                         1                             A1   
2                         1                             A1   
3                         1                             A2   
4                         1                             A2   

            sale_price  sale_date  
0           764,000.00 2022-06-30  
1         1,098,000.00 2022-08-19  
2                 0.00 2022-04-20  
3           890,000.00 2022-01-03  
4                 0.00 2022-12-27

## 03.6 Harmonise column datatypes in df_p2

In [350]:
# Recall datatypes in df_p2
df_p2.dtypes

borough                                    int64
neighborhood                              object
building_class_category                   object
tax_class_at_present                      object
block                                      int64
lot                                        int64
easement                                  object
building_class_at_present                 object
address                                   object
apartment_number                          object
zip_code                                   int64
residential_units                          int64
commercial_units                           int64
total_units                                int64
land_square_feet                         float64
gross_square_feet                        float64
year_built                                 int64
tax_class_at_time_of_sale                  int64
building_class_at_time_of_sale            object
sale_price                               float64
sale_date           

In [351]:
# Convert borough, block, lot and tax_class_at_time_of_sale to string
df_p2['borough'] = df_p2['borough'].astype('str')
df_p2['block'] = df_p2['block'].astype('str')
df_p2['lot'] = df_p2['lot'].astype('str')
df_p2['tax_class_at_time_of_sale'] = df_p2['tax_class_at_time_of_sale'].astype('str')

In [352]:
# Check whether conversion has worked
df_p2.dtypes

borough                                   object
neighborhood                              object
building_class_category                   object
tax_class_at_present                      object
block                                     object
lot                                       object
easement                                  object
building_class_at_present                 object
address                                   object
apartment_number                          object
zip_code                                   int64
residential_units                          int64
commercial_units                           int64
total_units                                int64
land_square_feet                         float64
gross_square_feet                        float64
year_built                                 int64
tax_class_at_time_of_sale                 object
building_class_at_time_of_sale            object
sale_price                               float64
sale_date           

## 03.7 Harmonise column datatypes in df_p3

In [353]:
# Recall datatypes in df_p3
df_p3.dtypes

borough                                    int64
neighborhood                              object
building_class_category                   object
tax_class_at_present                      object
block                                      int64
lot                                        int64
easement                                  object
building_class_at_present                 object
address                                   object
apartment_number                          object
zip_code                                   int64
residential_units                          int64
commercial_units                           int64
total_units                                int64
land_square_feet                         float64
gross_square_feet                        float64
year_built                                 int64
tax_class_at_time_of_sale                  int64
building_class_at_time_of_sale            object
sale_price                               float64
sale_date           

In [354]:
# Convert borough, block, lot and tax_class_at_time_of_sale to string
df_p3['borough'] = df_p3['borough'].astype('str')
df_p3['block'] = df_p3['block'].astype('str')
df_p3['lot'] = df_p3['lot'].astype('str')
df_p3['tax_class_at_time_of_sale'] = df_p3['tax_class_at_time_of_sale'].astype('str')

In [355]:
# Check whether conversion has worked
df_p3.dtypes

borough                                   object
neighborhood                              object
building_class_category                   object
tax_class_at_present                      object
block                                     object
lot                                       object
easement                                  object
building_class_at_present                 object
address                                   object
apartment_number                          object
zip_code                                   int64
residential_units                          int64
commercial_units                           int64
total_units                                int64
land_square_feet                         float64
gross_square_feet                        float64
year_built                                 int64
tax_class_at_time_of_sale                 object
building_class_at_time_of_sale            object
sale_price                               float64
sale_date           

## 03.8 Harmonise column datatypes in df_p4

In [356]:
# Recall datatypes in df_p4
df_p4.dtypes

borough                                    int64
neighborhood                              object
building_class_category                   object
tax_class_at_present                      object
block                                      int64
lot                                        int64
easement                                  object
building_class_at_present                 object
address                                   object
apartment_number                          object
zip_code                                   int64
residential_units                          int64
commercial_units                           int64
total_units                                int64
land_square_feet                         float64
gross_square_feet                        float64
year_built                                 int64
tax_class_at_time_of_sale                  int64
building_class_at_time_of_sale            object
sale_price                               float64
sale_date           

In [357]:
# Convert borough, block, lot and tax_class_at_time_of_sale to string
df_p4['borough'] = df_p4['borough'].astype('str')
df_p4['block'] = df_p4['block'].astype('str')
df_p4['lot'] = df_p4['lot'].astype('str')
df_p4['tax_class_at_time_of_sale'] = df_p4['tax_class_at_time_of_sale'].astype('str')

In [358]:
# Check whether conversion has worked
df_p4.dtypes

borough                                   object
neighborhood                              object
building_class_category                   object
tax_class_at_present                      object
block                                     object
lot                                       object
easement                                  object
building_class_at_present                 object
address                                   object
apartment_number                          object
zip_code                                   int64
residential_units                          int64
commercial_units                           int64
total_units                                int64
land_square_feet                         float64
gross_square_feet                        float64
year_built                                 int64
tax_class_at_time_of_sale                 object
building_class_at_time_of_sale            object
sale_price                               float64
sale_date           

## 03.9 Harmonise column datatypes in df_roll

In [359]:
# Recall datatypes in df_roll
df_roll.dtypes

borough                                  float64
neighborhood                              object
building_class_category                   object
tax_class_at_present                      object
block                                    float64
lot                                      float64
easement                                 float64
building_class_at_present                 object
address                                   object
apartment_number                          object
zip_code                                 float64
residential_units                        float64
commercial_units                         float64
total_units                              float64
land_square_feet                         float64
gross_square_feet                        float64
year_built                               float64
tax_class_at_time_of_sale                float64
building_class_at_time_of_sale            object
sale_price                               float64
sale_date           

In [360]:
# Convert borough, block, lot, easement and tax_class_at_time_of_sale to string
df_roll['borough'] = df_roll['borough'].astype('str').str[:-2]
df_roll['block'] = df_roll['block'].astype('str').str[:-2]
df_roll['lot'] = df_roll['lot'].astype('str').str[:-2]
df_roll['easement'] = df_roll['easement'].astype('str').str[:-2]
df_roll['tax_class_at_time_of_sale'] = df_roll['tax_class_at_time_of_sale'].astype('str').str[:-2]

# Convert zip_code to int
df_roll['zip_code'] = df_roll['zip_code'].astype(int, errors='ignore')

# Convert columns on numbers of units to int
df_roll['residential_units'] = df_roll['residential_units'].astype(int, errors='ignore')
df_roll['commercial_units'] = df_roll['commercial_units'].astype(int, errors='ignore')
df_roll['total_units'] = df_roll['total_units'].astype(int, errors='ignore')

# Convert year_built to int
df_roll['year_built'] = df_roll['year_built'].astype(int, errors='ignore')

In [361]:
# Check whether conversion has worked
df_roll.dtypes

borough                                   object
neighborhood                              object
building_class_category                   object
tax_class_at_present                      object
block                                     object
lot                                       object
easement                                  object
building_class_at_present                 object
address                                   object
apartment_number                          object
zip_code                                 float64
residential_units                        float64
commercial_units                         float64
total_units                              float64
land_square_feet                         float64
gross_square_feet                        float64
year_built                               float64
tax_class_at_time_of_sale                 object
building_class_at_time_of_sale            object
sale_price                               float64
sale_date           

Conversion has not worked for zip_code, residential_units, commercial_units, total_units and year_built. 

In [362]:
# Check zip_code for missing values
df_roll['zip_code'].isna().sum()

7

In [363]:
# Inspect rows with missing values for zip_code
print(df_roll.loc[df_roll['zip_code'].isna()])

      borough   neighborhood     building_class_category tax_class_at_present  \
4753        5  OAKWOOD-BEACH  05 TAX CLASS 1 VACANT LAND                   1B   
7742        4        ARVERNE       29 COMMERCIAL GARAGES                    4   
7743        4        ARVERNE       29 COMMERCIAL GARAGES                    4   
75362       3   SPRING CREEK  05 TAX CLASS 1 VACANT LAND                   1B   
75363       3   SPRING CREEK  05 TAX CLASS 1 VACANT LAND                   1B   
75364       3   SPRING CREEK  05 TAX CLASS 1 VACANT LAND                   1B   
75365       3   SPRING CREEK  05 TAX CLASS 1 VACANT LAND                   1B   

       block  lot easement building_class_at_present                  address  \
4753    4785    1        n                        V0     N/A PROMENADE AVENUE   
7742   16013    1        n                        G7  N/A BEACH CHANNEL DRIVE   
7743   16013    1        n                        G7  N/A BEACH CHANNEL DRIVE   
75362   4585  165        n 

Full address is not available for rows with missing zip code, hence zip code cannot be deduced from address. To remain consistent in handling missing zip_codes, missing values will be imputed as 0 (same approach as for df_p1).

In [364]:
# Imputing 0 for missing values in zip_code
df_roll['zip_code'].fillna(0, inplace=True)

In [365]:
# Check whether missing values were imputed
df_roll['zip_code'].isna().sum()

0

In [366]:
# Check residential_units for missing values
df_roll['residential_units'].isna().sum()

21247

In [367]:
# Inspect some rows with missing values for residential_units
print(df_roll.loc[df_roll['residential_units'].isna()])

      borough          neighborhood         building_class_category  \
174         5              ANNADALE        46 CONDO STORE BUILDINGS   
477         5  ARROCHAR-SHORE ACRES  10 COOPS - ELEVATOR APARTMENTS   
478         5  ARROCHAR-SHORE ACRES  10 COOPS - ELEVATOR APARTMENTS   
479         5  ARROCHAR-SHORE ACRES  10 COOPS - ELEVATOR APARTMENTS   
480         5  ARROCHAR-SHORE ACRES  10 COOPS - ELEVATOR APARTMENTS   
...       ...                   ...                             ...   
84383       2              WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   
84384       2              WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   
84385       2              WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   
84386       2              WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   
84387       2              WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   

      tax_class_at_present block   lot easement building_class_at_present  \
174                      4  6244  1002        n                       

In [368]:
# Get basic descriptive statistics on residential_units
df_roll['residential_units'].describe()

count              63,144.00
mean                    3.55
std                    25.91
min                     0.00
25%                     1.00
50%                     1.00
75%                     2.00
max                 2,039.00
Name: residential_units, dtype: float64

In [369]:
# Check skewness of residential_units
df_roll['residential_units'].skew()

22.95875394456787

As distribution in residential_units is skewed and the number of missing values is high (ca. 25% of all rows) and dropping them might delete valuable information in other columns, missing values will be imputed with median. 

In [370]:
# Impute missing values in residential_units with median
df_roll['residential_units'].fillna(df_roll['residential_units'].median(), inplace=True)

In [371]:
# Check whether missing values were imputed
df_roll['residential_units'].isna().sum()

0

In [372]:
# Check commercial_units for missing values
df_roll['commercial_units'].isna().sum()

37253

In [373]:
# Inspect some rows with missing values for commercial_units
print(df_roll.loc[df_roll['commercial_units'].isna()])

      borough   neighborhood         building_class_category  \
158         5       ANNADALE           04 TAX CLASS 1 CONDOS   
395         5  ARDEN HEIGHTS           04 TAX CLASS 1 CONDOS   
396         5  ARDEN HEIGHTS           04 TAX CLASS 1 CONDOS   
397         5  ARDEN HEIGHTS           04 TAX CLASS 1 CONDOS   
398         5  ARDEN HEIGHTS           04 TAX CLASS 1 CONDOS   
...       ...            ...                             ...   
84383       2       WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   
84384       2       WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   
84385       2       WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   
84386       2       WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   
84387       2       WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   

      tax_class_at_present block   lot easement building_class_at_present  \
158                     1A  6226  1002        n                        R3   
395                     1A  5742  1006        n                        R3   


In [374]:
# Get basic descriptive statistics on commercial_units
df_roll['commercial_units'].describe()

count              47,138.00
mean                    0.31
std                     6.51
min                     0.00
25%                     0.00
50%                     0.00
75%                     0.00
max                 1,178.00
Name: commercial_units, dtype: float64

In [375]:
# Check skewness of commercial_units
df_roll['commercial_units'].skew()

137.25283940826756

As distribution in residential_units is highly skewed and the number of missing values is high (ca. 44% of all rows) and dropping them might delete valuable information in other columns, missing values will be imputed with median. 

In [376]:
# Impute missing values in commercial_units with median
df_roll['commercial_units'].fillna(df_roll['commercial_units'].median(), inplace=True)

In [377]:
# Check whether missing values were imputed
df_roll['commercial_units'].isna().sum()

0

In [378]:
# Check total_units for missing values
df_roll['total_units'].isna().sum()

18514

In [379]:
# Inspect some rows with missing values for total_units
print(df_roll.loc[df_roll['total_units'].isna()])

      borough          neighborhood         building_class_category  \
477         5  ARROCHAR-SHORE ACRES  10 COOPS - ELEVATOR APARTMENTS   
478         5  ARROCHAR-SHORE ACRES  10 COOPS - ELEVATOR APARTMENTS   
479         5  ARROCHAR-SHORE ACRES  10 COOPS - ELEVATOR APARTMENTS   
480         5  ARROCHAR-SHORE ACRES  10 COOPS - ELEVATOR APARTMENTS   
481         5  ARROCHAR-SHORE ACRES  10 COOPS - ELEVATOR APARTMENTS   
...       ...                   ...                             ...   
84383       2              WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   
84384       2              WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   
84385       2              WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   
84386       2              WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   
84387       2              WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   

      tax_class_at_present block lot easement building_class_at_present  \
477                      2  2833  31        n                        D4 

Missing values for total_units will be deduced from residential_units + commercial_units.

In [380]:
# Impute missing values in total_units
df_roll['total_units'].fillna((df_roll['residential_units']+df_roll['commercial_units']), inplace=True)

In [381]:
# Check whether missing values were imputed
df_roll['total_units'].isna().sum()

0

In [382]:
# Print row at index 84387 to check whether correct value was imputed (expected value is 1.0)
print(df_roll.iloc[[84387]])

      borough neighborhood         building_class_category  \
84387       2     WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   

      tax_class_at_present block lot easement building_class_at_present  \
84387                    2  3398  97        n                        D4   

                       address apartment_number             zip_code  \
84387  4295 WEBSTER AVENUE; L4              nan            10,470.00   

         residential_units     commercial_units          total_units  \
84387                 1.00                 0.00                 1.00   

       land_square_feet  gross_square_feet           year_built  \
84387               NaN                NaN             1,957.00   

      tax_class_at_time_of_sale building_class_at_time_of_sale  \
84387                         2                             D4   

                sale_price  sale_date  
84387           904,225.00 2022-06-30  


In [383]:
# Check year_built for missing values
df_roll['year_built'].isna().sum()

5508

In [384]:
# Inspect some rows with missing values for year_built
print(df_roll.loc[df_roll['year_built'].isna()])

      borough    neighborhood     building_class_category  \
159         5        ANNADALE  05 TAX CLASS 1 VACANT LAND   
160         5        ANNADALE  05 TAX CLASS 1 VACANT LAND   
162         5        ANNADALE  05 TAX CLASS 1 VACANT LAND   
163         5        ANNADALE  05 TAX CLASS 1 VACANT LAND   
165         5        ANNADALE  05 TAX CLASS 1 VACANT LAND   
...       ...             ...                         ...   
84271       2  WILLIAMSBRIDGE       29 COMMERCIAL GARAGES   
84272       2  WILLIAMSBRIDGE       29 COMMERCIAL GARAGES   
84274       2  WILLIAMSBRIDGE   31 COMMERCIAL VACANT LAND   
84275       2  WILLIAMSBRIDGE   31 COMMERCIAL VACANT LAND   
84340       2        WOODLAWN  05 TAX CLASS 1 VACANT LAND   

      tax_class_at_present block lot easement building_class_at_present  \
159                     1B  6209  29        n                        V0   
160                     1B  6242  17        n                        V0   
162                     1B  6261  56      

To remain consistent with handling missing values in df_p1, rows with missing values for year_built will be dropped (ca. 6,5% of all rows).

In [385]:
# Drop rows with missing values in year_built
df_roll.dropna(subset=['year_built'], inplace=True)

In [386]:
# Check whether missing values were dropped
df_roll['year_built'].isna().sum()

0

No missing values remain in the columns not converted to integers. 

In [387]:
# Convert zip_code to int
df_roll['zip_code'] = df_roll['zip_code'].astype(int, errors='ignore')

# Convert columns on numbers of units to int
df_roll['residential_units'] = df_roll['residential_units'].astype(int, errors='ignore')
df_roll['commercial_units'] = df_roll['commercial_units'].astype(int, errors='ignore')
df_roll['total_units'] = df_roll['total_units'].astype(int, errors='ignore')

# Convert year_built to int
df_roll['year_built'] = df_roll['year_built'].astype(int, errors='ignore')

In [388]:
# Check datatypes in df_roll
df_roll.dtypes

borough                                   object
neighborhood                              object
building_class_category                   object
tax_class_at_present                      object
block                                     object
lot                                       object
easement                                  object
building_class_at_present                 object
address                                   object
apartment_number                          object
zip_code                                   int64
residential_units                          int64
commercial_units                           int64
total_units                                int64
land_square_feet                         float64
gross_square_feet                        float64
year_built                                 int64
tax_class_at_time_of_sale                 object
building_class_at_time_of_sale            object
sale_price                               float64
sale_date           

In [389]:
# Check head of df_roll
df_roll.head()

borough neighborhood  building_class_category tax_class_at_present block  \
0       5     ANNADALE  01 ONE FAMILY DWELLINGS                    1  5391   
1       5     ANNADALE  01 ONE FAMILY DWELLINGS                    1  5395   
2       5     ANNADALE  01 ONE FAMILY DWELLINGS                    1  5395   
3       5     ANNADALE  01 ONE FAMILY DWELLINGS                    1  5396   
4       5     ANNADALE  01 ONE FAMILY DWELLINGS                    1  5401   

  lot easement building_class_at_present              address  \
0   7        n                        A5      4732 AMBOY ROAD   
1   4        n                        A1      26 EDWIN STREET   
2  32        n                        A1  541 SYCAMORE STREET   
3  41        n                        A1    21 TALLMAN STREET   
4  42        n                        A2    265 HAROLD AVENUE   

  apartment_number  zip_code  residential_units  commercial_units  \
0              nan     10312                  1                 0   
1              nan     10312                  1                 0   
2              nan     10312                  1                 0   
3              nan     10312                  1                 0   
4              nan     10312                  1                 0   

   total_units     land_square_feet    gross_square_feet  year_built  \
0            1             3,655.00               910.00        2002   
1            1             7,654.00             2,277.00        1980   
2            1            13,320.00             4,696.00        1985   
3            1             9,968.00             3,940.00        1990   
4            1             8,190.00             2,100.00        1980   

  tax_class_at_time_of_sale building_class_at_time_of_sale  \
0                         1                             A5   
1                         1                             A1   
2                         1                             A1   
3                         1                             A1   
4                         1                             A2   

            sale_price  sale_date  
0           764,000.00 2022-06-30  
1         1,098,000.00 2022-08-19  
2                 0.00 2022-04-20  
3         1,275,000.00 2023-03-17  
4           385,000.00 2023-02-16

# 04 Final check for mixed-type columns before merging

In [390]:
# Check again for mixed-type columns in df_p1
for col in df_p1.columns.tolist():
  weird = (df_p1[[col]].applymap(type) != df_p1[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_p1[weird]) > 0:
    print (col)

In [391]:
# Check again for mixed-type columns in df_p2
for col in df_p2.columns.tolist():
  weird = (df_p2[[col]].applymap(type) != df_p2[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_p2[weird]) > 0:
    print (col)

In [392]:
# Check again for mixed-type columns in df_p3
for col in df_p3.columns.tolist():
  weird = (df_p3[[col]].applymap(type) != df_p3[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_p3[weird]) > 0:
    print (col)

In [393]:
# Check again for mixed-type columns in df_p4
for col in df_p4.columns.tolist():
  weird = (df_p4[[col]].applymap(type) != df_p4[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_p4[weird]) > 0:
    print (col)

In [394]:
# Check again for mixed-type columns in df_roll
for col in df_roll.columns.tolist():
  weird = (df_roll[[col]].applymap(type) != df_roll[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_roll[weird]) > 0:
    print (col)

# 05 Merging all dataframes into one

In [395]:
# Create list of dataframes
list_dfs = [df_p1, df_p2, df_p3, df_p4, df_roll]

# Concatenate dataframes
df = pd.concat(list_dfs, ignore_index=True)

In [396]:
# Check head of df
df.head()

borough neighborhood  building_class_category tax_class_at_present block  \
0       5     ANNADALE  01 ONE FAMILY DWELLINGS                    1  5391   
1       5     ANNADALE  01 ONE FAMILY DWELLINGS                    1  5395   
2       5     ANNADALE  01 ONE FAMILY DWELLINGS                    1  5395   
3       5     ANNADALE  01 ONE FAMILY DWELLINGS                    1  5399   
4       5     ANNADALE  01 ONE FAMILY DWELLINGS                    1  5402   

  lot easement building_class_at_present              address  \
0   7        n                        A5      4732 AMBOY ROAD   
1   4        n                        A1      26 EDWIN STREET   
2  32        n                        A1  541 SYCAMORE STREET   
3  37        n                        A2   255 KOCH BOULEVARD   
4  17        n                        A2      6 WEAVER STREET   

  apartment_number  zip_code  residential_units  commercial_units  \
0              nan     10312                  1                 0   
1              nan     10312                  1                 0   
2              nan     10312                  1                 0   
3              nan     10312                  1                 0   
4              nan     10312                  1                 0   

   total_units     land_square_feet    gross_square_feet  year_built  \
0            1             3,654.00               910.00        2002   
1            1             7,654.00             2,277.00        1980   
2            1            13,320.00             4,696.00        1985   
3            1             8,190.00             1,528.00        1970   
4            1            10,500.00             2,278.00        1980   

  tax_class_at_time_of_sale building_class_at_time_of_sale  \
0                         1                             A5   
1                         1                             A1   
2                         1                             A1   
3                         1                             A2   
4                         1                             A2   

            sale_price  sale_date  
0           764,000.00 2022-06-30  
1         1,098,000.00 2022-08-19  
2                 0.00 2022-04-20  
3           890,000.00 2022-01-03  
4                 0.00 2022-12-27

In [397]:
# Get info on df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1916261 entries, 0 to 1916260
Data columns (total 21 columns):
 #   Column                          Dtype         
---  ------                          -----         
 0   borough                         object        
 1   neighborhood                    object        
 2   building_class_category         object        
 3   tax_class_at_present            object        
 4   block                           object        
 5   lot                             object        
 6   easement                        object        
 7   building_class_at_present       object        
 8   address                         object        
 9   apartment_number                object        
 10  zip_code                        int64         
 11  residential_units               int64         
 12  commercial_units                int64         
 13  total_units                     int64         
 14  land_square_feet                float64       
 15

In [398]:
# Double-check whether concatenation worked
len(df) == len(df_p1) + len(df_p2) + len(df_p3) + len(df_p4) + len(df_roll)

True

In [399]:
# Double-check for mixed-type columns in df
for col in df.columns.tolist():
  weird = (df[[col]].applymap(type) != df[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df[weird]) > 0:
    print (col)

# 06 Data cleaning - merged dataframe

## 06.1 Address duplicates

In [400]:
# Check for duplicates
df_dups = df[df.duplicated()]

In [401]:
# Check size of df_dups
df_dups.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 78621 entries, 243301 to 1916260
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype         
---  ------                          --------------  -----         
 0   borough                         78621 non-null  object        
 1   neighborhood                    78621 non-null  object        
 2   building_class_category         78621 non-null  object        
 3   tax_class_at_present            78621 non-null  object        
 4   block                           78621 non-null  object        
 5   lot                             78621 non-null  object        
 6   easement                        78621 non-null  object        
 7   building_class_at_present       78621 non-null  object        
 8   address                         78621 non-null  object        
 9   apartment_number                78621 non-null  object        
 10  zip_code                        78621 non-null  int64         


There are 78621 full duplicates in the dataframe which can be dropped.

In [402]:
# Drop full duplicates from df_no_dups
df_no_dups = df.drop_duplicates()

In [403]:
# Check for accuracy of dropping duplicates
len(df) == len(df_dups) + len(df_no_dups)

True

In [404]:
# Get info on df_no_dups
df_no_dups.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1837640 entries, 0 to 1916259
Data columns (total 21 columns):
 #   Column                          Dtype         
---  ------                          -----         
 0   borough                         object        
 1   neighborhood                    object        
 2   building_class_category         object        
 3   tax_class_at_present            object        
 4   block                           object        
 5   lot                             object        
 6   easement                        object        
 7   building_class_at_present       object        
 8   address                         object        
 9   apartment_number                object        
 10  zip_code                        int64         
 11  residential_units               int64         
 12  commercial_units                int64         
 13  total_units                     int64         
 14  land_square_feet                float64       
 15

## 06.2 Check for missing values

In [405]:
df_no_dups['borough'].isna().sum()

0

In [406]:
df_no_dups['neighborhood'].isna().sum()

0

In [407]:
df_no_dups['building_class_category'].isna().sum()

0

In [408]:
df_no_dups['tax_class_at_present'].isna().sum()

0

In [409]:
df_no_dups['block'].isna().sum()

0

In [410]:
df_no_dups['lot'].isna().sum()

0

In [411]:
df_no_dups['easement'].isna().sum()

0

In [412]:
df_no_dups['building_class_at_present'].isna().sum()

0

In [413]:
df_no_dups['address'].isna().sum()

0

In [414]:
df_no_dups['apartment_number'].isna().sum()

0

In [415]:
df_no_dups['zip_code'].isna().sum()

0

In [416]:
df_no_dups['year_built'].isna().sum()

0

In [417]:
df_no_dups['tax_class_at_time_of_sale'].isna().sum()

0

In [418]:
df_no_dups['building_class_at_time_of_sale'].isna().sum()

0

In [419]:
df_no_dups['sale_date'].isna().sum()

0

In [420]:
df_no_dups['residential_units'].isna().sum()

0

In [421]:
df_no_dups['commercial_units'].isna().sum()

0

In [422]:
df_no_dups['total_units'].isna().sum()

0

In [423]:
df_no_dups['land_square_feet'].isna().sum()

116061

In [424]:
df_no_dups['gross_square_feet'].isna().sum()

116060

In [425]:
df_no_dups['sale_price'].isna().sum()

0

In [426]:
df_no_dups['sale_date'].isna().sum()

0

## 06.3 Get descriptive statistics for columns with missing values

In [427]:
# Descriptive statistics for land_square_feet
df_no_dups['land_square_feet'].describe()

count           1,721,579.00
mean                3,694.01
std               291,427.74
min                     0.00
25%                     0.00
50%                 1,975.00
75%                 2,900.00
max           214,755,710.00
Name: land_square_feet, dtype: float64

In [428]:
# Get skew for land_square_feet
df_no_dups['land_square_feet'].skew()

699.5853671838145

In [429]:
# Descriptive statistics for gross_square_feet
df_no_dups['gross_square_feet'].describe()

count           1,721,580.00
mean                4,053.04
std                41,801.49
min                     0.00
25%                     0.00
50%                 1,346.00
75%                 2,400.00
max            14,962,152.00
Name: gross_square_feet, dtype: float64

In [430]:
# Get skew for gross_square_feet
df['gross_square_feet'].skew()

152.70894903047784

## 06.7 Create subsets with missing values

In [431]:
# Create subsets
df_nan_land_square = df_no_dups[df_no_dups['land_square_feet'].isna() == True]
df_nan_gross_square = df_no_dups[df_no_dups['gross_square_feet'].isna() == True]

In [432]:
# Inspect head of subset I
df_nan_land_square.head()

borough   neighborhood   building_class_category tax_class_at_present  \
180       5       ANNADALE     04 TAX CLASS 1 CONDOS                   1C   
185       5       ANNADALE  46 CONDO STORE BUILDINGS                    4   
186       5       ANNADALE  46 CONDO STORE BUILDINGS                    4   
454       5  ARDEN HEIGHTS     04 TAX CLASS 1 CONDOS                   1A   
455       5  ARDEN HEIGHTS     04 TAX CLASS 1 CONDOS                   1A   

    block   lot easement building_class_at_present  \
180  6226  1101        n                        R6   
185  6244  1001        n                        RK   
186  6244  1002        n                        RK   
454  6017  1003        n                        R3   
455  6017  1037        n                        R3   

                        address apartment_number  zip_code  residential_units  \
180        736 ANNADALE ROAD; B                B     10312                  1   
185        885 ANNADALE ROAD; 1                1     10312                  1   
186        885 ANNADALE ROAD; 2                2     10312                  1   
454       55 ROLLING HILL GREEN              nan     10312                  1   
455  60 ROLLING HILL GREEN; N/A              nan     10312                  1   

     commercial_units  total_units  land_square_feet  gross_square_feet  \
180                 0            1               NaN                NaN   
185                 1            1               NaN                NaN   
186                 1            1               NaN                NaN   
454                 0            1               NaN                NaN   
455                 0            1               NaN                NaN   

     year_built tax_class_at_time_of_sale building_class_at_time_of_sale  \
180        2012                         1                             R6   
185        1975                         4                             RK   
186        1975                         4                             RK   
454        1979                         1                             R3   
455        1979                         1                             R3   

              sale_price  sale_date  
180           810,000.00 2022-01-12  
185           150,000.00 2022-01-10  
186           440,000.00 2022-10-24  
454                 0.00 2022-03-23  
455           480,000.00 2022-12-08

In [433]:
# Inspect head of subset II
df_nan_gross_square.head()

borough   neighborhood   building_class_category tax_class_at_present  \
180       5       ANNADALE     04 TAX CLASS 1 CONDOS                   1C   
185       5       ANNADALE  46 CONDO STORE BUILDINGS                    4   
186       5       ANNADALE  46 CONDO STORE BUILDINGS                    4   
454       5  ARDEN HEIGHTS     04 TAX CLASS 1 CONDOS                   1A   
455       5  ARDEN HEIGHTS     04 TAX CLASS 1 CONDOS                   1A   

    block   lot easement building_class_at_present  \
180  6226  1101        n                        R6   
185  6244  1001        n                        RK   
186  6244  1002        n                        RK   
454  6017  1003        n                        R3   
455  6017  1037        n                        R3   

                        address apartment_number  zip_code  residential_units  \
180        736 ANNADALE ROAD; B                B     10312                  1   
185        885 ANNADALE ROAD; 1                1     10312                  1   
186        885 ANNADALE ROAD; 2                2     10312                  1   
454       55 ROLLING HILL GREEN              nan     10312                  1   
455  60 ROLLING HILL GREEN; N/A              nan     10312                  1   

     commercial_units  total_units  land_square_feet  gross_square_feet  \
180                 0            1               NaN                NaN   
185                 1            1               NaN                NaN   
186                 1            1               NaN                NaN   
454                 0            1               NaN                NaN   
455                 0            1               NaN                NaN   

     year_built tax_class_at_time_of_sale building_class_at_time_of_sale  \
180        2012                         1                             R6   
185        1975                         4                             RK   
186        1975                         4                             RK   
454        1979                         1                             R3   
455        1979                         1                             R3   

              sale_price  sale_date  
180           810,000.00 2022-01-12  
185           150,000.00 2022-01-10  
186           440,000.00 2022-10-24  
454                 0.00 2022-03-23  
455           480,000.00 2022-12-08

In [434]:
# Inspect tail of subset I
df_nan_land_square.tail()

borough neighborhood         building_class_category  \
1916221       2     WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   
1916225       2     WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   
1916243       2     WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   
1916245       2     WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   
1916253       2     WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   

        tax_class_at_present block lot easement building_class_at_present  \
1916221                    2  3368  10        n                        D4   
1916225                    2  3368  10        n                        D4   
1916243                    2  3398  87        n                        D4   
1916245                    2  3398  97        n                        D4   
1916253                    2  3398  97        n                        D4   

                                  address apartment_number  zip_code  \
1916221  4320 VAN CORTLANDT PARK EAST; 4G              nan     10470   
1916225  4320 VAN CORTLANDT PARK EAST; 6N              nan     10470   
1916243              4315 WEBSTER AVE; 6M              nan     10470   
1916245              4295 WEBSTER AVE; 2F              nan     10470   
1916253           4295 WEBSTER AVENUE; 4K              nan     10470   

         residential_units  commercial_units  total_units  land_square_feet  \
1916221                  1                 0            1               NaN   
1916225                  1                 0            1               NaN   
1916243                  1                 0            1               NaN   
1916245                  1                 0            1               NaN   
1916253                  1                 0            1               NaN   

         gross_square_feet  year_built tax_class_at_time_of_sale  \
1916221                NaN        1958                         2   
1916225                NaN        1958                         2   
1916243                NaN        1958                         2   
1916245                NaN        1957                         2   
1916253                NaN        1957                         2   

        building_class_at_time_of_sale           sale_price  sale_date  
1916221                             D4           155,000.00 2023-03-03  
1916225                             D4           195,000.00 2023-02-15  
1916243                             D4           220,000.00 2023-03-09  
1916245                             D4           250,000.00 2023-02-02  
1916253                             D4           114,500.00 2023-03-01

In [435]:
# Inspect tail of subset II
df_nan_gross_square.tail()

borough neighborhood         building_class_category  \
1916221       2     WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   
1916225       2     WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   
1916243       2     WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   
1916245       2     WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   
1916253       2     WOODLAWN  10 COOPS - ELEVATOR APARTMENTS   

        tax_class_at_present block lot easement building_class_at_present  \
1916221                    2  3368  10        n                        D4   
1916225                    2  3368  10        n                        D4   
1916243                    2  3398  87        n                        D4   
1916245                    2  3398  97        n                        D4   
1916253                    2  3398  97        n                        D4   

                                  address apartment_number  zip_code  \
1916221  4320 VAN CORTLANDT PARK EAST; 4G              nan     10470   
1916225  4320 VAN CORTLANDT PARK EAST; 6N              nan     10470   
1916243              4315 WEBSTER AVE; 6M              nan     10470   
1916245              4295 WEBSTER AVE; 2F              nan     10470   
1916253           4295 WEBSTER AVENUE; 4K              nan     10470   

         residential_units  commercial_units  total_units  land_square_feet  \
1916221                  1                 0            1               NaN   
1916225                  1                 0            1               NaN   
1916243                  1                 0            1               NaN   
1916245                  1                 0            1               NaN   
1916253                  1                 0            1               NaN   

         gross_square_feet  year_built tax_class_at_time_of_sale  \
1916221                NaN        1958                         2   
1916225                NaN        1958                         2   
1916243                NaN        1958                         2   
1916245                NaN        1957                         2   
1916253                NaN        1957                         2   

        building_class_at_time_of_sale           sale_price  sale_date  
1916221                             D4           155,000.00 2023-03-03  
1916225                             D4           195,000.00 2023-02-15  
1916243                             D4           220,000.00 2023-03-09  
1916245                             D4           250,000.00 2023-02-02  
1916253                             D4           114,500.00 2023-03-01

Rows with missing land and gross square feet are kept as some other columns in those rows contain valuable information. Missing values in land and gross square feet will be imputed with median as both have a highly skewed distribution.

## 06.8 Address missing values

In [436]:
# Impute missing values in land_square_feet with median
df_no_dups['land_square_feet'].fillna(df_no_dups['land_square_feet'].median(), inplace=True)

/var/folders/xf/prw7mx913rn2xzxlywvr1_jc0000gn/T/ipykernel_44932/3852708212.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_no_dups['land_square_feet'].fillna(df_no_dups['land_square_feet'].median(), inplace=True)


In [437]:
# Impute missing values in gross_square_feet with median
df_no_dups['gross_square_feet'].fillna(df_no_dups['gross_square_feet'].median(), inplace=True)

/var/folders/xf/prw7mx913rn2xzxlywvr1_jc0000gn/T/ipykernel_44932/3253382794.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_no_dups['gross_square_feet'].fillna(df_no_dups['gross_square_feet'].median(), inplace=True)


### Check whether missing values were filled

In [438]:
df_no_dups['land_square_feet'].isna().sum()

0

In [439]:
df_no_dups['gross_square_feet'].isna().sum()

0

# 07 Creating flags

## 07.1 Sale prices == 0

Cf. information from the NYC Department of Finance:

A 0 dollar sale price indicates that there was a transfer of ownership without a cash consideration. There can be a number of reasons for a 0 dollar sale_price including transfers of ownership from parents to children.

In [440]:
# Flag sale prices that are 0
df_no_dups.loc[df_no_dups['sale_price'] == 0, 'sale_price_flag'] = 'transf_ownership'

/var/folders/xf/prw7mx913rn2xzxlywvr1_jc0000gn/T/ipykernel_44932/2928222934.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_no_dups.loc[df_no_dups['sale_price'] == 0, 'sale_price_flag'] = 'transf_ownership'


In [441]:
# Check creation of flag column
df_no_dups.head(3)

borough neighborhood  building_class_category tax_class_at_present block  \
0       5     ANNADALE  01 ONE FAMILY DWELLINGS                    1  5391   
1       5     ANNADALE  01 ONE FAMILY DWELLINGS                    1  5395   
2       5     ANNADALE  01 ONE FAMILY DWELLINGS                    1  5395   

  lot easement building_class_at_present              address  \
0   7        n                        A5      4732 AMBOY ROAD   
1   4        n                        A1      26 EDWIN STREET   
2  32        n                        A1  541 SYCAMORE STREET   

  apartment_number  zip_code  residential_units  commercial_units  \
0              nan     10312                  1                 0   
1              nan     10312                  1                 0   
2              nan     10312                  1                 0   

   total_units     land_square_feet    gross_square_feet  year_built  \
0            1             3,654.00               910.00        2002   
1            1             7,654.00             2,277.00        1980   
2            1            13,320.00             4,696.00        1985   

  tax_class_at_time_of_sale building_class_at_time_of_sale  \
0                         1                             A5   
1                         1                             A1   
2                         1                             A1   

            sale_price  sale_date   sale_price_flag  
0           764,000.00 2022-06-30               NaN  
1         1,098,000.00 2022-08-19               NaN  
2                 0.00 2022-04-20  transf_ownership

In [442]:
# Check correct creation of flag
(df_no_dups[df_no_dups['sale_price'] == 0].value_counts().sum()) == (df_no_dups[df_no_dups['sale_price_flag'] == 'transf_ownership'].value_counts().sum())

True

## 07.2 Imputing borough names

In [443]:
# Rename column borough
df_no_dups = df_no_dups.rename(columns={'borough': 'borough_code'})

In [444]:
# Check renaming
df_no_dups.head(2)

borough_code neighborhood  building_class_category tax_class_at_present  \
0            5     ANNADALE  01 ONE FAMILY DWELLINGS                    1   
1            5     ANNADALE  01 ONE FAMILY DWELLINGS                    1   

  block lot easement building_class_at_present          address  \
0  5391   7        n                        A5  4732 AMBOY ROAD   
1  5395   4        n                        A1  26 EDWIN STREET   

  apartment_number  zip_code  residential_units  commercial_units  \
0              nan     10312                  1                 0   
1              nan     10312                  1                 0   

   total_units     land_square_feet    gross_square_feet  year_built  \
0            1             3,654.00               910.00        2002   
1            1             7,654.00             2,277.00        1980   

  tax_class_at_time_of_sale building_class_at_time_of_sale  \
0                         1                             A5   
1                         1                             A1   

            sale_price  sale_date sale_price_flag  
0           764,000.00 2022-06-30             NaN  
1         1,098,000.00 2022-08-19             NaN

In [445]:
# Create column with borough name
df_no_dups.loc[df_no_dups['borough_code'] == '1', 'borough_name'] = 'Manhattan'
df_no_dups.loc[df_no_dups['borough_code'] == '2', 'borough_name'] = 'Bronx'
df_no_dups.loc[df_no_dups['borough_code'] == '3', 'borough_name'] = 'Brooklyn'
df_no_dups.loc[df_no_dups['borough_code'] == '4', 'borough_name'] = 'Queens'
df_no_dups.loc[df_no_dups['borough_code'] == '5', 'borough_name'] = 'Staten Island'

In [446]:
# Check creation of borough name column
df_no_dups.head(3)

borough_code neighborhood  building_class_category tax_class_at_present  \
0            5     ANNADALE  01 ONE FAMILY DWELLINGS                    1   
1            5     ANNADALE  01 ONE FAMILY DWELLINGS                    1   
2            5     ANNADALE  01 ONE FAMILY DWELLINGS                    1   

  block lot easement building_class_at_present              address  \
0  5391   7        n                        A5      4732 AMBOY ROAD   
1  5395   4        n                        A1      26 EDWIN STREET   
2  5395  32        n                        A1  541 SYCAMORE STREET   

  apartment_number  zip_code  residential_units  commercial_units  \
0              nan     10312                  1                 0   
1              nan     10312                  1                 0   
2              nan     10312                  1                 0   

   total_units     land_square_feet    gross_square_feet  year_built  \
0            1             3,654.00               910.00        2002   
1            1             7,654.00             2,277.00        1980   
2            1            13,320.00             4,696.00        1985   

  tax_class_at_time_of_sale building_class_at_time_of_sale  \
0                         1                             A5   
1                         1                             A1   
2                         1                             A1   

            sale_price  sale_date   sale_price_flag   borough_name  
0           764,000.00 2022-06-30               NaN  Staten Island  
1         1,098,000.00 2022-08-19               NaN  Staten Island  
2                 0.00 2022-04-20  transf_ownership  Staten Island

In [447]:
# Check correct creation of borogh name column for Manhattan
(df_no_dups[df_no_dups['borough_code'] == '1'].value_counts().sum()) == (df_no_dups[df_no_dups['borough_name'] == 'Manhattan'].value_counts().sum())

True

In [448]:
# Check correct creation of borogh name column for Bronx
(df_no_dups[df_no_dups['borough_code'] == '2'].value_counts().sum()) == (df_no_dups[df_no_dups['borough_name'] == 'Bronx'].value_counts().sum())

True

In [449]:
# Check correct creation of borogh name column for Brooklyn
(df_no_dups[df_no_dups['borough_code'] == '3'].value_counts().sum()) == (df_no_dups[df_no_dups['borough_name'] == 'Brooklyn'].value_counts().sum())

True

In [450]:
# Check correct creation of borogh name column for Queens
(df_no_dups[df_no_dups['borough_code'] == '4'].value_counts().sum()) == (df_no_dups[df_no_dups['borough_name'] == 'Queens'].value_counts().sum())

True

In [451]:
# Check correct creation of borogh name column for Staten Island
(df_no_dups[df_no_dups['borough_code'] == '5'].value_counts().sum()) == (df_no_dups[df_no_dups['borough_name'] == 'Staten Island'].value_counts().sum())

True

In [452]:
# Check for NaN in borough name
df_no_dups['borough_name'].isna().sum()

0

In [453]:
# Double-check for mixed-type columns in df_no_dups
for col in df_no_dups.columns.tolist():
  weird = (df_no_dups[[col]].applymap(type) != df_no_dups[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_no_dups[weird]) > 0:
    print (col)

sale_price_flag


In [454]:
# Convert sale_price_flag to str
df_no_dups['sale_price_flag'] = df_no_dups['sale_price_flag'].astype('str')

In [455]:
# Double-check for mixed-type columns in df_no_dups again
for col in df_no_dups.columns.tolist():
  weird = (df_no_dups[[col]].applymap(type) != df_no_dups[[col]].iloc[0].apply(type)).any(axis = 1)
  if len (df_no_dups[weird]) > 0:
    print (col)

In [456]:
df_no_dups.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1837640 entries, 0 to 1916259
Data columns (total 23 columns):
 #   Column                          Dtype         
---  ------                          -----         
 0   borough_code                    object        
 1   neighborhood                    object        
 2   building_class_category         object        
 3   tax_class_at_present            object        
 4   block                           object        
 5   lot                             object        
 6   easement                        object        
 7   building_class_at_present       object        
 8   address                         object        
 9   apartment_number                object        
 10  zip_code                        int64         
 11  residential_units               int64         
 12  commercial_units                int64         
 13  total_units                     int64         
 14  land_square_feet                float64       
 15

# 08 Data consistency checks

In [457]:
# Unique values in borough_code
df_no_dups['borough_code'].value_counts(dropna=False)

4    573572
3    514912
1    427278
5    170192
2    151686
Name: borough_code, dtype: int64

In [458]:
# Unique values in neighborhood
df_no_dups['neighborhood'].value_counts(dropna=False)

MIDTOWN WEST                 51353
FLUSHING-NORTH               38662
UPPER EAST SIDE (59-79)      29724
UPPER WEST SIDE (59-79)      27378
BEDFORD STUYVESANT           25908
                             ...  
EAST RIVER                       2
PELHAM BAY                       2
3004                             2
3019                             1
1021                             1
Name: neighborhood, Length: 516, dtype: int64

In [459]:
# Unique values in building_class_category
df_no_dups['building_class_category'].value_counts(dropna=False)

01  ONE FAMILY HOMES                            207756
02  TWO FAMILY HOMES                            192213
10  COOPS - ELEVATOR APARTMENTS                 192181
13  CONDOS - ELEVATOR APARTMENTS                177206
01 ONE FAMILY DWELLINGS                         105143
                                                 ...  
40 SELECTED GOVERNMENTAL FACILITIES                  5
39 TRANSPORTATION FACILITIES                         4
40 SELECTED GOVERNMENTAL FACILITIES                  3
39 TRANSPORTATION FACILITIES                         3
11 SPECIAL CONDO BILLING LOTS                        1
Name: building_class_category, Length: 145, dtype: int64

In [460]:
# Unique values in tax_class_at_present
df_no_dups['tax_class_at_present'].value_counts(dropna=False)

1      862920
2      635885
4      155892
2A      56813
2C      36147
1A      29433
2B      18948
1B      18620
        17004
1C       2567
         1979
1D        922
nan       391
3         119
Name: tax_class_at_present, dtype: int64

In [461]:
# Unique values in block
df_no_dups['block'].value_counts(dropna=False)

1027     17823
1009     10515
1006      8523
1171      5967
16        4904
         ...  
16006        1
16330        1
9364         1
7068         1
4279         1
Name: block, Length: 13628, dtype: int64

In [462]:
# Unique values in lot
df_no_dups['lot'].value_counts(dropna=False)

1       84687
37      26652
20      21060
12      21037
23      21002
        ...  
5774        1
5129        1
6103        1
6117        1
4963        1
Name: lot, Length: 5888, dtype: int64

In [463]:
# Unique values in easement
df_no_dups['easement'].value_counts(dropna=False)

     1404644
n     432983
E         13
Name: easement, dtype: int64

In [464]:
# Unique values in building_class_at_present
df_no_dups['building_class_at_present'].value_counts(dropna=False)

D4    269286
R4    244721
A1    149540
A5    121576
B2    111693
       ...  
P4         2
Y7         2
I2         2
CM         1
U5         1
Name: building_class_at_present, Length: 216, dtype: int64

In [465]:
# Unique values in address
df_no_dups['address'].value_counts(dropna=False)

870 7 AVENUE                                 13510
102 WEST 57TH STREET                          7496
1335 AVENUE OF THE AMERIC                     3431
200 WEST 56TH   STREET                        2705
1335 6 AVENUE                                 2699
                                             ...  
80-51 233 STREET                                 1
80-34 235TH   STREET                             1
236-07 SEWARD AVE                                1
234-08 SEWARD AVENUE                             1
4295 WEBSTER AVE; 2F                             1
Name: address, Length: 1206966, dtype: int64

In [466]:
# Unique values in apartment_number
df_no_dups['apartment_number'].value_counts(dropna=False)

                1031279
nan              345595
                  69440
TIMES              6614
4                  5351
                 ...   
36 B                  1
PH-AS                 1
28 B                  1
3RS                   1
913A                  1
Name: apartment_number, Length: 29370, dtype: int64

In [467]:
# Unique values in zip_code
df_no_dups['zip_code'].value_counts(dropna=False)

10019    54970
10314    30459
10023    28267
11234    24841
11375    24498
         ...  
10281        1
11452        1
11359        1
11315        1
10436        1
Name: zip_code, Length: 248, dtype: int64

In [468]:
# Unique values in year_built
df_no_dups['year_built'].value_counts(dropna=False)

0       171904
1920    138609
1930    113022
1925     98003
1910     77412
         ...  
220          1
1821         1
1867         1
1802         1
1648         1
Name: year_built, Length: 214, dtype: int64

In [469]:
# Unique values in tax_class_at_time_of_sale
df_no_dups['tax_class_at_time_of_sale'].value_counts(dropna=False)

1    922697
2    752320
4    162464
3       159
Name: tax_class_at_time_of_sale, dtype: int64

In [470]:
# Unique values in building_class_at_time_of_sale
df_no_dups['building_class_at_time_of_sale'].value_counts(dropna=False)

D4    269559
R4    247787
A1    151673
A5    121398
B2    110206
       ...  
Y7         2
N3         2
CM         1
Y9         1
Y5         1
Name: building_class_at_time_of_sale, Length: 215, dtype: int64

In [471]:
# Unique values in sale_date
df_no_dups['sale_date'].value_counts(dropna=False)

2006-08-31    1629
2003-02-20    1203
2008-10-02     991
2012-09-27     980
2004-06-30     880
              ... 
2020-04-19       1
2016-11-27       1
2017-06-04       1
2019-10-13       1
2020-07-05       1
Name: sale_date, Length: 7393, dtype: int64

In [472]:
# Unique values in residential_units
df_no_dups['residential_units'].value_counts(dropna=False)

1       788788
0       464203
2       370056
3       109541
4        29907
         ...  
550          1
399          1
1328         1
635          1
2039         1
Name: residential_units, Length: 520, dtype: int64

In [473]:
# Unique values in commercial_units
df_no_dups['commercial_units'].value_counts(dropna=False)

0      1664927
1       127399
2        26771
3         6327
4         3383
        ...   
153          1
730          1
80           1
92           1
390          1
Name: commercial_units, Length: 196, dtype: int64

In [474]:
# Unique values in total_units
df_no_dups['total_units'].value_counts(dropna=False)

1       877261
2       373544
0       336570
3       128385
4        32598
         ...  
551          1
361          1
955          1
1091         1
2039         1
Name: total_units, Length: 547, dtype: int64

In [475]:
# Unique values in land_square_feet
df_no_dups['land_square_feet'].value_counts(dropna=False)

     0.00    638569
 1,975.00    117150
 2,000.00     86529
 2,500.00     79017
 4,000.00     64536
              ...  
23,294.00         1
53,654.00         1
29,107.00         1
26,403.00         1
28,165.00         1
Name: land_square_feet, Length: 20159, dtype: int64

In [476]:
# Unique values in gross_square_feet
df_no_dups['gross_square_feet'].value_counts(dropna=False)

      0.00    667472
  1,346.00    116247
112,850.00      9221
  2,400.00      9029
  3,000.00      8058
               ...  
191,330.00         1
 78,474.00         1
158,456.00         1
 23,870.00         1
  7,318.00         1
Name: gross_square_feet, Length: 23879, dtype: int64

In [477]:
# Unique values in sale_price
df_no_dups['sale_price'].value_counts(dropna=False)

         0.00    545197
        10.00     14450
   450,000.00      9580
   400,000.00      9361
   550,000.00      8717
                  ...  
   462,157.00         1
   423,343.00         1
20,863,475.00         1
   172,996.00         1
   226,173.00         1
Name: sale_price, Length: 106971, dtype: int64

In [478]:
# Unique values in sale_price_flag
df_no_dups['sale_price_flag'].value_counts(dropna=False)

nan                 1292443
transf_ownership     545197
Name: sale_price_flag, dtype: int64

In [479]:
# Unique values in borough_name
df_no_dups['borough_name'].value_counts(dropna=False)

Queens           573572
Brooklyn         514912
Manhattan        427278
Staten Island    170192
Bronx            151686
Name: borough_name, dtype: int64

## 08.1 Further cleaning to address inconsistencies

Inconsistencies in apartment_number will not be addressed as the column won't be relevant for the analysis.

Further cleaning will be done on:

tax_class_at present: nan, empty values and NaN will be merged to NaN. However, as the variable is time-variant and it cannot be guaranteed that the information provided is accurate at the time of the analysis, it is generally better not to work too much with this column, but with tax_class_at_time_of_sale instead as this variable is time-invariant.

easement: values of n and empty values will be merged to NaN.

year_built: To remain consistent with handling missing values in year_built earlier, rows with 0 for year_built will be dropped (ca. 9% of all rows).

In [480]:
# In tax_class_at_present replace nan with NaN
df_no_dups['tax_class_at_present'] = df_no_dups['tax_class_at_present'].replace('nan','NaN')

In [481]:
# In tax_class_at_present replace empty values with NaN
df_no_dups['tax_class_at_present'] = df_no_dups['tax_class_at_present'].replace(r'^\s*$','NaN', regex=True)

In [482]:
# Check unique values in tax_class_at_present again
df_no_dups['tax_class_at_present'].value_counts(dropna=False)

1      862920
2      635885
4      155892
2A      56813
2C      36147
1A      29433
NaN     19374
2B      18948
1B      18620
1C       2567
1D        922
3         119
Name: tax_class_at_present, dtype: int64

In [483]:
# In easement replace n with NaN
df_no_dups['easement'] = df_no_dups['easement'].replace('n','NaN')

In [484]:
# In easement replace empty values with NaN
df_no_dups['easement'] = df_no_dups['easement'].replace(r'^\s*$','NaN', regex=True)

In [485]:
# Check unique values in easement again
df_no_dups['easement'].value_counts(dropna=False)

NaN    1837627
E           13
Name: easement, dtype: int64

In [486]:
# Drop rows with year_built 0
df_no_dups = df_no_dups.loc[df_no_dups['year_built'] !=0]

In [487]:
# Check unique values in year_built again
df_no_dups['year_built'].value_counts(dropna=False)

1920    138609
1930    113022
1925     98003
1910     77412
1950     68378
         ...  
1821         1
220          1
1030         1
1802         1
1648         1
Name: year_built, Length: 213, dtype: int64

In [488]:
# Get shape of df_no_dups (expected no. of rows: 1665736)
df_no_dups.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1665736 entries, 0 to 1916259
Data columns (total 23 columns):
 #   Column                          Non-Null Count    Dtype         
---  ------                          --------------    -----         
 0   borough_code                    1665736 non-null  object        
 1   neighborhood                    1665736 non-null  object        
 2   building_class_category         1665736 non-null  object        
 3   tax_class_at_present            1665736 non-null  object        
 4   block                           1665736 non-null  object        
 5   lot                             1665736 non-null  object        
 6   easement                        1665736 non-null  object        
 7   building_class_at_present       1665736 non-null  object        
 8   address                         1665736 non-null  object        
 9   apartment_number                1665736 non-null  object        
 10  zip_code                        1665736 no

# 09 Basic descriptive statistics I

In [489]:
# Change options for display of scientific notation
pd.options.display.float_format = '{:20,.2f}'.format

In [490]:
# Get minimum, maximum, mean and median for numeric columns
df_no_dups.describe()

zip_code    residential_units     commercial_units  \
count         1,665,736.00         1,665,736.00         1,665,736.00   
mean             10,863.51                 2.51                 0.24   
std                 594.52                34.43                 7.74   
min                   0.00                 0.00                 0.00   
25%              10,306.00                 1.00                 0.00   
50%              11,211.00                 1.00                 0.00   
75%              11,361.00                 2.00                 0.00   
max              11,697.00            20,811.00             4,964.00   

               total_units     land_square_feet    gross_square_feet  \
count         1,665,736.00         1,665,736.00         1,665,736.00   
mean                  2.76             3,710.35             4,272.09   
std                  35.39           295,916.55            42,464.03   
min                   0.00                 0.00                 0.00   
25%                   1.00                 0.00                 0.00   
50%                   1.00             1,980.00             1,404.00   
75%                   2.00             2,900.00             2,430.00   
max              20,811.00       214,755,710.00        14,962,152.00   

                year_built           sale_price  
count         1,665,736.00         1,665,736.00  
mean              1,948.71           943,824.98  
std                  33.78        11,588,090.64  
min                 220.00                 0.00  
25%               1,925.00                 0.00  
50%               1,940.00           350,000.00  
75%               1,969.00           680,000.00  
max               2,022.00     4,111,111,766.00

year_built cannot be 220, this is likely erroneous data. Therefore, the row with year_built 202 will be dropped. Furthermore, as the first settlements along the Hudson were established in 1624 year_built cannot be lower than that. This is the lowest possible minimum year_built. All values below 1624 will therefore be dropped, too.

It is irritating that land_square_feet and gross_square_feet have minimum values of 0. The NYC Department of Finance glossary of terms says the following: 

Land square feet is "the land area of the property listed in square feet".
Gross square feet is "the total area of all the floors of a building as measured from the exterior surfaces of the outside walls of the building, including the land area and space within any building or structure on the property".

Hence, land_square_feet should always be greater than 0 and gross_square_feet should at minimum be equal to land_square_feet. This inconsistency is accepted for now, but will be further investigated at a later stage of the analysis.

In [491]:
# Get minimum sale_date
df_no_dups['sale_date'].min()

Timestamp('2003-01-01 00:00:00')

In [492]:
# Get maximum of sale_date
df_no_dups['sale_date'].max()

Timestamp('2023-03-31 00:00:00')

## 09.1 Further cleaning I based on insights from descriptive statistics

check how many rows with year below 1624; then create drop these rows if they're not too many; ensure resulting df has right shape

In [493]:
# Create df with year_built <1624
df_bad_year = df_no_dups.loc[df_no_dups['year_built'] <1624]

In [494]:
# Get shape of df_bad_year
df_bad_year.shape

(14, 23)

In [495]:
# Drop rows with year_built <1624
df_no_dups = df_no_dups.loc[df_no_dups['year_built'] >=1624]

In [496]:
# Get shape of df_no_dups (expected no. of rows: 1665722)
df_no_dups.shape

(1665722, 23)

# 10 Basic descriptive statistics II

In [497]:
# Get minimum, maximum, mean and median for numeric columns again
df_no_dups.describe()

zip_code    residential_units     commercial_units  \
count         1,665,722.00         1,665,722.00         1,665,722.00   
mean             10,863.51                 2.51                 0.24   
std                 594.52                34.43                 7.74   
min                   0.00                 0.00                 0.00   
25%              10,306.00                 1.00                 0.00   
50%              11,211.00                 1.00                 0.00   
75%              11,361.00                 2.00                 0.00   
max              11,697.00            20,811.00             4,964.00   

               total_units     land_square_feet    gross_square_feet  \
count         1,665,722.00         1,665,722.00         1,665,722.00   
mean                  2.76             3,710.36             4,272.11   
std                  35.39           295,917.79            42,464.20   
min                   0.00                 0.00                 0.00   
25%                   1.00                 0.00                 0.00   
50%                   1.00             1,980.00             1,404.00   
75%                   2.00             2,900.00             2,430.00   
max              20,811.00       214,755,710.00        14,962,152.00   

                year_built           sale_price  
count         1,665,722.00         1,665,722.00  
mean              1,948.72           943,820.87  
std                  33.67        11,588,136.56  
min               1,648.00                 0.00  
25%               1,925.00                 0.00  
50%               1,940.00           350,000.00  
75%               1,969.00           680,000.00  
max               2,022.00     4,111,111,766.00

In [498]:
# Get info on df_no_dups
df_no_dups.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1665722 entries, 0 to 1916259
Data columns (total 23 columns):
 #   Column                          Non-Null Count    Dtype         
---  ------                          --------------    -----         
 0   borough_code                    1665722 non-null  object        
 1   neighborhood                    1665722 non-null  object        
 2   building_class_category         1665722 non-null  object        
 3   tax_class_at_present            1665722 non-null  object        
 4   block                           1665722 non-null  object        
 5   lot                             1665722 non-null  object        
 6   easement                        1665722 non-null  object        
 7   building_class_at_present       1665722 non-null  object        
 8   address                         1665722 non-null  object        
 9   apartment_number                1665722 non-null  object        
 10  zip_code                        1665722 no

# 11 Drop columns that are irrelevant for the analysis

In [499]:
# Drop all columns irrelevant to the ensuing analysis
df_no_dups_final = df_no_dups.drop(columns = ['block', 'lot', 'address', 'apartment_number', 'zip_code'])

In [500]:
# Get info on df_no_dups_final
df_no_dups_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1665722 entries, 0 to 1916259
Data columns (total 18 columns):
 #   Column                          Non-Null Count    Dtype         
---  ------                          --------------    -----         
 0   borough_code                    1665722 non-null  object        
 1   neighborhood                    1665722 non-null  object        
 2   building_class_category         1665722 non-null  object        
 3   tax_class_at_present            1665722 non-null  object        
 4   easement                        1665722 non-null  object        
 5   building_class_at_present       1665722 non-null  object        
 6   residential_units               1665722 non-null  int64         
 7   commercial_units                1665722 non-null  int64         
 8   total_units                     1665722 non-null  int64         
 9   land_square_feet                1665722 non-null  float64       
 10  gross_square_feet               1665722 no

# 12 Export dataframes

In [501]:
# Define path2 for exporting
path2 = r'/Users/DanielaDietmayr/Library/CloudStorage/OneDrive-Personal/2023-05-07_NYC property sales/02_Data/02_Prepared data'

In [502]:
# Export df_no_dups_final as csv file
df_no_dups_final.to_csv(os.path.join(path2, '2023-05-14_df.csv'), index=False)

In [503]:
# Export df_no_dups_final as pickle file
df_no_dups_final.to_pickle(os.path.join(path2, '2023-05-14_df.pkl'))